### DISCUSSION TITLE
Why do I get an error when using go1.21?

### DISCUSSION THREAD

**Discussion by SimFG** [golangci/golangci-lint-action#1055] [Q&A]
The following is my workflow file:
```
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.18
      - name: golangci-lint core
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./core
          args: --timeout=5m --out-format=colored-line-number ./...
          skip-cache: true
      - name: golangci-lint server
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./server
          args: --timeout=5m --out-format=colored-line-number ./...
          skip-cache: true
```
I don't have a go.mod file in my root directory, but there are in the core and server directories. If I use go1.18, github action will work fine, but if I use go1.21, I will get an error that the go file cannot be found.
![Ies8QYWC7d](https://github.com/golangci/golangci-lint/assets/21985684/84b689cd-913a-4208-8ffd-d987e45f8d56)
