### DISCUSSION TITLE
Error: can't load config: gci is a formatter

### DISCUSSION THREAD

**Discussion by ambersun1234** [golangci/golangci-lint-action#1223] [Q&A] [answered]
### Welcome

- [x] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### Description of the problem

The command `$ golangci-lint fmt --enable gci --enable gofmt -d ./...` works well locally but not in GitHub Action\
It'll give the below error message

```shell
Error: can't load config: gci is a formatter
  Failed executing command with error: can't load config: gci is a formatter
```

### Version of golangci-lint

2.0.2

### Version of the GitHub Action

2.323.0

### Workflow file

<details>

```yml
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.21

    - name: Run golangci-lint Format Check
      uses: golangci/golangci-lint-action@v7
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        version: v2.0.2
        args: fmt --enable gci --enable gofmt --timeout=10m
```

</details>

### Golangci-lint configuration

<details>

```yml
version: "2"
linters:
  enable:
    - gosec
    - misspell
    - prealloc
    - tagalign
  disable:
    - errcheck
  settings:
    gosec:
      excludes:
        - "G304"
        - "G104"
formatters:
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - prefix(github.com/MY-COMPANY)
        - default
    gofmt:
      simplify: true
```

</details>

### Go version

1.21

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>
