### DISCUSSION TITLE
Error running with config downloaded from remote

### DISCUSSION THREAD

**Discussion by dopey** [golangci/golangci-lint-action#539] [Q&A] [answered]
I'm trying to run the github action like so: 

```
        name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: 'v1.45.2'
          args: --config <(curl https://some.file.yonder.yaml) --timeout=30m
```

and I'm getting the following error `/bin/sh: 1: Syntax error: "(" unexpected`. When I run `golangci-lint run --config <(curl https://some.file.yonder.yaml) --timeout=30m` from the command line this works without issue. Is this a supported pattern in the github action?
