### DISCUSSION TITLE
Linter action not working properly

### DISCUSSION THREAD

**Discussion by rokerzfirst101** [golangci/golangci-lint-action#716] [Q&A]
The linter action keeps on throwing this error, whereas whenever I run the linter locally no issue is found

<img width="670" alt="Screenshot 2023-03-31 at 1 01 47 PM" src="https://user-images.githubusercontent.com/33196098/229053915-22c43578-35ff-4258-a7e7-ddcaea409a40.png">

Following is the Job setup:
```  
code_quality:
    name: 🎖 Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.x'
          cache: false

      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          skip-cache: true
```
