### DISCUSSION TITLE
Golang CI Lint Action taking a long time to execute on CI machine

### DISCUSSION THREAD

**Discussion by AM1729** [golangci/golangci-lint-action#789] [Q&A]
Hi, so we are using github actions CI on self-hosted setup, and using the official `golangci/golangci-lint-action` for using this. However for fairly large codebase it's taking ~ 50 - 60 mins in github-actions CI, whereas it's taking ~ 11 mins in AWS Codebuild.
I also tried running this as a Docker Container, still the same.

I have tried increasing the compute (CPU), and am currently using 8v CPU with 16G memory for the main container in the ECS task (i.e. I am running Github Action as self-hosted Runner in a Docker container), however still getting the same result. 

There seems to be no significant difference between using 8V CPU -  16G memory and 4V CPU - 8G memorym which is counter intuitive. While using 8V CPU machine, I also had increased the no. of threads to 8, still no luck. 

Github Action Config:

```
steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout=30m --new-from-rev=${{ github.event.pull_request.base.sha }} --fast=true
```

Configuration File that I am using:
```
run:
  # default concurrency is a available CPU number
  concurrency: 8

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  skip-dirs:
    - deployment
    - configs
    - test
    - (^|/)vendor($|/)
    - (^|/)third_party($|/)
    - (^|/)testdata($|/)
    - (^|/)examples($|/)
    - (^|/)Godeps($|/)
    - (^|/)builtin($|/)

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true


linters-settings:
  # TODO: Check gci, gofumpt, gomodguard, stylecheck

  depguard:
    # https://github.com/OpenPeeDeeP/depguard
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus

  dogsled:
    # checks assignments with too many blank identifiers; default is 2
    max-blank-identifiers: 2

  dupl:
    # tokens count to trigger issue
    threshold: 200

  funlen:
    lines: 300
    statements: 150

  goconst:
    # minimal length of string constant, 3 by default
    min-len: 5
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 5

  gosec:
    includes:
      - G101 # Look for hard coded credentials
      - G107 # Url provided to HTTP request as taint input
      - G108 # Profiling endpoint automatically exposed on /debug/pprof
      - G109 # Potential Integer overflow made by strconv.Atoi result conversion to int16/32
      - G110 # Potential DoS vulnerability via decompression bomb
      - G201 # SQL query construction using format string
      - G202 # SQL query construction using string concatenation 
      - G203 # Use of unescaped data in HTML templates
      - G305 # File traversal when extracting zip/tar archive
      - G402 # Look for bad TLS connection settings

    excludes:
      - G102
      - G103
      - G104
      - G106
      - G401 # Detect the usage of DES, RC4, MD5 or SHA1
      - G404 # Insecure random number source (rand)
      - G501
      - G502
      - G503
      - G504
      - G505
    exclude-generated: true

  gocritic:
    enabled-tags:
      - performance
    disabled-checks:
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845

  gocyclo:
    min-complexity: 40

  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8

  gomnd:
    settings:
      mnd:
        # the list of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
        checks: argument,case,condition,operation,return,assign

  govet:
    # report about shadowed variables
    check-shadowing: true

  misspell:
    locale: UK
    ignore-words:
      - initialized
      - serialized
      - finalized
      - utilize
      - materialize
      - personalize
      - color

  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 180
    # tab width in spaces.
    tab-width: 4

  nolintlint:
    allow-leading-space: true # don't require machine-readable nolint directives (i.e. with no leading space)
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  
  errcheck:
    check-type-assertions: false
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - noctx
    - rowserrcheck
    - staticcheck
    - structcheck
    - typecheck
    - unparam
    - unused
    - varcheck
    - whitespace
    - gomodguard
    - sqlclosecheck

  # don't enable: (as suggested in golangci docs)
  # - gomnd
  # - asciicheck
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - nestif
  # - prealloc
  # - testpackage
  # - wsl

  # disabled linters:
  # - durationcheck
  # - wastedassign
  # - nolintlint
  # - dogsled
  # - nakedret
  # - exportloopref
  # - gci
  # - gofumpt
  # - goheader
  # - gomodguard
  # - goprintffuncname
  # - nlreturn
  # - scopelint


issues:
  # Show only new issues created after git revision `REV`
  new-from-rev: ${{ github.event.pull_request.base.sha }}
  
  max-issues-per-linter: 2000
  max-same-issues: 100

  exclude-rules:
    # Exclude lll issues for long lines with go:generate
    # Exclude golint issues for "Rpc" to "RPC" conversion
    # Exclude golint warnings prompting for "Id" to "ID" conversion
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - misspell
      text: ".*serialized.*misspelling"
    - linters:
        - golint
      text: ".*Rpc.* should be .*RPC"
    - linters:
        - golint
      text: ".*Id.* should be .*ID*"

    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - lll
        - funlen
        - exhaustive
        - gomnd
        - gocritic
        - goconst
        - lll
        - misspell
        - nakedret
        - dogsled
        - dupl

severity:
  # Default value is empty string.
  # Set the default severity for issues. If severity rules are defined and the issues
  # do not match or no severity is provided to the rule this will be the default
  # severity applied. Severities should match the supported severity names of the
  # selected out format.
  default-severity: warning

  # The default value is false.
  # If set to true severity-rules regular expressions become case sensitive.
  case-sensitive: false

  # When a list of severity rules are provided, severity information will be added to lint
  # issues. Severity rules have the same filtering capability as exclude rules except you
  # are allowed to specify one matcher per severity rule.
  # Only affects out formats that support setting severity information.
  # rules:
  #   - linters:
  #     - dupl
  #     severity: info
  rules:
    - linters:
      - errcheck
      - gomodguard
      - ineffassign
      severity: error
    - linters:
      - funlen
      - exhaustive
      - gomnd
      - goconst
      - gocyclo
      - lll
      - misspell
      - nakedret
      - dogsled
      - dupl
      severity: info
    - linters:
      - gocritic
      - deadcode
      - gochecknoinits
      - gofmt
      - goimports
      - gosimple
      - nolintlint
      - sqlclosecheck
      - staticcheck
      - unparam
      - unused
      - varcheck
      - whitespace
      - structcheck
      - golint
      - durationcheck
      - wastedassign
      severity: warning

service:
  golangci-lint-version: 1.30.0
  prepare: []
```

Please help in suggesting what can go wrong here ? Like am I missing anything here ?

**Comment by bombsimon** [comment]
Are you using/hitting the cache as expected? Also what version of `golangci-lint` are you using? Are you using the same version in Codebuild? [v1.47.1 is known to be slow](https://github.com/golangci/golangci-lint/issues/2997) but is fixed.

Maybe some posts in https://github.com/golangci/golangci-lint-action/issues/297 might help you troubleshoot.

**Comment by AM1729** [comment]
@bombsimon  Thank you for your response.

As in the action I am using, I am specifying this to be `v1.53`, however the action is deciding to use `v1.53.3`

```
- name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
```
