### DISCUSSION TITLE
Using the action with multi-module workspaces

### DISCUSSION THREAD

**Discussion by matthewhughes-uw** [golangci/golangci-lint-action#873] [Q&A]
Hi, I'm working in a repo that uses [multi-module workspaces](https://go.dev/doc/tutorial/workspaces) and was wondering if there's any support for such a setup with this action?

For some context, to run locally list the local modules (from `go.work`) and pass their paths to `golangci-lint run`:

    go list -m -f '{{.Dir}}' | sed 's|$|/...|g' | xargs golangci-lint run

**Comment by mjlshen** [comment]
I've found a way to do this, for example with a step like:
```yaml
      - name: 'Lint'
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: 'v1.56.2'
          args: '-v $(go list -f ''{{.Dir}}/...'' -m | xargs)'
```

Which does the equivalent of `golangci-lint run -v $(go list -f '{{.Dir}}/...' -m | xargs)`
