### DISCUSSION TITLE
How can I restrict pull request diffs to only be linted?

### DISCUSSION THREAD

**Discussion by hiroyuki-fujii-td** [golangci/golangci-lint-action#943] [Q&A] [answered]
By default,  when I run golangci-lint on Github Actions, golangci-lint applies all linters to all repository files.
I wanna know how to restrict target files only pull-req diff.

<details>
<summary>.golangci.yaml</summary>

```
run:
  deadline: 5m

linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - lll
    - misspell
    - prealloc
    - staticcheck
    - typecheck
    - unused
    - whitespace

linters-settings:
  lll:
    line-length: 140


```
</details>

<details>
<summary>golangci-lint.yaml</summary>

```
name: golangci-lint
on:
  push:
    branches:
      - develop
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
```

</details>

best regards.
