### ISSUE TITLE
invalid go version '1.21.9': must match format 1.23\n"

### ISSUE THREAD

**Issue by amery** [golangci/golangci-lint-action#1046]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

`1.21.9` on `go.mod` makes the action explode but `go get` itself appends the `.9`

```
$ go get -v ./...
go: upgraded go 1.21 => 1.21.9
```

it works fine when run manually (`make tidy` on the branch)

### Version of golangci-lint

1.58.2

### Version of the GitHub Action

v6

### Workflow file

<details>

```yml
<add your file content here>
```

</details>

### Golangci-lint configuration

<details>

```yml
run:
  deadline: 5m
  allow-parallel-runners: true

linters-settings:
  govet:
    enable=fieldalignment: true
  revive:
    rules:
      # The following rules are recommended https://github.com/mgechev/revive#recommended-configuration
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      #
      # Rules in addition to the recommended configuration above.
      #
      - name: bool-literal-in-expr
      - name: constant-logical-expr

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
```

</details>

### Go version

1.21.9

### Code example or link to a public repository

https://github.com/amery/nanorpc/tree/pr-amery-chores
