### ISSUE TITLE
Static type checks doesn't include embedded types with github action

### ISSUE THREAD

**Issue by dorimon-1** [golangci/golangci-lint-action#1058]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

Well I hope im not mistaken and there isn't any issues regarding this.
Whenever I'm doing a check on my code base which contains a type with embedded types in it.
ex:
```go
type FtpClient struct {
	*goftp.Client
	*config.FtpConfiguration
}
```
I get a linting error only when doing a check with golangci-lint and I get these errors:
```
Error: ftp/ftp.go:61:39: client.FtpServerPath undefined (type *FtpClient has no field or method FtpServerPath) (typecheck)
  		path := fmt.Sprintf("%s/%s", client.FtpServerPath, file)
  		                                    ^
  Error: ftp/ftp.go:62:16: client.Retrieve undefined (type *FtpClient has no field or method Retrieve) (typecheck)
  		err = client.Retrieve(path, buffer)
  		             ^
  Error: ftp/ftp.go:70:23: client.ReadDir undefined (type *FtpClient has no field or method ReadDir) (typecheck)
  	files, err := client.ReadDir(client.FtpServerPath)
```
My building is passing just fine and I don't get any linting on my code editor

### Version of golangci-lint

1.59

### Version of the GitHub Action

latest? unsure what versions there are

### Workflow file

<details>

```yml
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

```

</details>

### Golangci-lint configuration

<details>

```yml
<add your file content here>
```

</details>

### Go version

1.22.3

### Code example or link to a public repository

<details>

```go
type FtpClient struct {
	*goftp.Client
	*config.FtpConfiguration
}

client, err := goftp.DialConfig(ftpConfig, config.FtpServerURL)

```
repo: https://github.com/KJone1/ImageElevator/blob/master/ftp/ftp.go

</details>

**Comment by ldez** [comment]
Hello,

I recommend reading https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors

**Comment by ldez** [comment]
:thinking: I'm trying to understand the behavior inside your CI.

https://github.com/KJone1/ImageElevator/actions/runs/9423135394/job/25960911614

**Comment by ldez** [comment]
Maybe it's a side effect of the divergence between your module name `github.com/Kjone1/imageElevator` and your repo name `https://github.com/KJone1/ImageElevator` :thinking:

**Comment by ldez** [comment]
Do you depend on cgo?

**Comment by ldez** [comment]
Yes, you are depending on cgo:
- https://github.com/KJone1/ImageElevator/blob/8a157b63a67c8aa2941fc9a9e686580f2dfab268/go.mod#L6C2-L6C29
- https://github.com/containers/image?tab=readme-ov-file#building
- https://github.com/KJone1/ImageElevator/blob/8a157b63a67c8aa2941fc9a9e686580f2dfab268/.github/workflows/go.yml#L27-L32

So you need to install the cgo dependency inside the golangci-lint workflow.
https://github.com/KJone1/ImageElevator/blob/8a157b63a67c8aa2941fc9a9e686580f2dfab268/.github/workflows/lint.yml

```yml
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'

      - name: ⚙️ Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y
          sudo apt-get install libbtrfs-dev -y
          sudo apt-get install libgpgme-dev -y

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
```
