### ISSUE TITLE
Does not work on go 1.23

### ISSUE THREAD

**Issue by mskonovalov** [golangci/golangci-lint-action#1086]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

Since yesterday our CI step started to fail. With no error messages, simply hanging forever.
Looking into logs it seems we now have go 1.23. And the last working commit was using 1.22
Not sure yet what could be the exact issue (will update my findings) but for now it just does not work completely

### Version of golangci-lint

1.59.1

### Version of the GitHub Action

v6

### Workflow file

<details>

```yml
  golangci:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
```

</details>

### Golangci-lint configuration

<details>

```yml
linters:
  # use all the default linters, plus the following
  enable:
    - goimports
```

</details>

### Go version

1.23

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>

**Comment by mskonovalov** [comment]
OK, https://github.com/golangci/golangci-lint/issues/4837
TBH not sure if there is anything that the action can do here.
Maybe it is possible to add check if go is 1.23 and lint is < 1.60 to print meaningful error message

**Comment by mskonovalov** [comment]
Just a tiny update:
it seems for 1.60.1 and go 1.23 it also does not work

```
  golangci:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60.1
```
I guess it is becuase of https://github.com/golangci/golangci-lint/issues/4908#issuecomment-2288716658
