### ISSUE TITLE
Question: only-new-issues does not work with merging PR

### ISSUE THREAD

**Issue by knrt10** [golangci/golangci-lint-action#110]
How can I make use of `only-new-issues`, in case when PR is merged to master. Any way can I use this?

It works fine with PR tests but throws error on merge

I have this use case and want to run in github action. Can someone please help?

```bash
golangci-lint run --new-from-rev=$$(git merge-base origin/master HEAD) ./...
```

**Comment by knrt10** [comment]
Problem was, how I was using actions/checkout@v2. Below code, fixed the issue for me

```yaml
- uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
```
