### ISSUE TITLE
Failed to load package goarch: could not load export data: internal error in importing \"internal/goarch\"

### ISSUE THREAD

**Issue by martiriera** [golangci/golangci-lint-action#1183]
### Welcome

- [x] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### Description of the problem

I'm trying to use the _Simple example_ on https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#how-to-use and I get this error:

```
Running error: can't run linter goanalysis_metalinter\nbuildir: failed to load package goarch: could not load export data: internal error in importing \"internal/goarch\" (unsupported version: 2); please report an issue
```

I found [this](https://github.com/golangci/golangci-lint-action/issues/434) old related issue but it's closed and I think it's already out of date.

Thanks in advance.

Full logs here:
```
Run golangci/golangci-lint-action@v6
  with:
    version: v1.60
    install-mode: binary
    github-token: ***
    verify: true
    only-new-issues: false
    skip-cache: false
    skip-save-cache: false
    problem-matchers: false
    cache-invalidation-interval: 7
prepare environment
  Checking for go.mod: go.mod
  Cache hit for: golangci-lint.cache-Linux-[2](https://github.com/martiriera/discogs-spotify/actions/runs/13474820665/job/37652665540#step:4:2)877-9aa87e5c487c5[3](https://github.com/martiriera/discogs-spotify/actions/runs/13474820665/job/37652665540#step:4:3)221c8b73ba7934c18b08ef11c1
  Received 6003 of 6003 (100.0%), 0.1 MBs/sec
  Cache Size: ~0 MB (6003 B)
  /usr/bin/tar -xf /home/runner/work/_temp/5cc5a0a1-3[4](https://github.com/martiriera/discogs-spotify/actions/runs/13474820665/job/37652665540#step:4:4)c9-4dc7-8db2-4190de9bda19/cache.tzst -P -C /home/runner/work/discogs-spotify/discogs-spotify --use-compress-program unzstd
  Cache restored successfully
  Restored cache for golangci-lint from key 'golangci-lint.cache-Linux-2877-9aa87e[5](https://github.com/martiriera/discogs-spotify/actions/runs/13474820665/job/37652665540#step:4:5)c487c53221c8b73ba7934c18b08ef11c1' in [6](https://github.com/martiriera/discogs-spotify/actions/runs/13474820665/job/37652665540#step:4:6)13ms
  Finding needed golangci-lint version...
  Requested golangci-lint 'v1.60', using 'v1.60.3', calculation took 35ms
  Installation mode: binary
  Installing golangci-lint binary v1.60.3...
  Downloading binary https://github.com/golangci/golangci-lint/releases/download/v1.60.3/golangci-lint-1.60.3-linux-amd64.tar.gz ...
  /usr/bin/tar xz --overwrite --warning=no-unknown-keyword --overwrite -C /home/runner -f /home/runner/work/_temp/a435544c-f4[8](https://github.com/martiriera/discogs-spotify/actions/runs/13474820665/job/37652665540#step:4:8)3-46fe-b32a-e0a5c8b00a6[9](https://github.com/martiriera/discogs-spotify/actions/runs/13474820665/job/37652665540#step:4:9)
  Installed golangci-lint into /home/runner/golangci-lint-1.60.3-linux-amd64/golangci-lint in 834ms
  Prepared env in 1483ms
run golangci-lint
  Running [/home/runner/golangci-lint-1.60.3-linux-amd64/golangci-lint config path] in [/home/runner/work/discogs-spotify/discogs-spotify] ...
  Running [/home/runner/golangci-lint-1.60.3-linux-amd64/golangci-lint run] in [/home/runner/work/discogs-spotify/discogs-spotify] ...
  level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package goarch: could not load export data: internal error in importing \"internal/goarch\" (unsupported version: 2); please report an issue"
  level=error msg="Running error: can't run linter goanalysis_metalinter\nbuildir: failed to load package goarch: could not load export data: internal error in importing \"internal/goarch\" (unsupported version: 2); please report an issue"
```

### Version of golangci-lint

golangci-lint-1.60.3-linux-amd64

### Version of the GitHub Action

golangci/golangci-lint-action@v6

### Workflow file

<details>

```yml
name: Pre-Merge

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  test:
    name: Test
    needs: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run tests
        run: go test -v ./...

```

</details>

### Golangci-lint configuration

None

### Go version

1.23.4

### Code example or link to a public repository

[discogs-spotify](https://github.com/martiriera/discogs-spotify)
