### ISSUE TITLE
Running error: can't run linter goanalysis_metalinter\nbuildir: failed to load package goarch: could not load export data: internal error in importing \"internal/goarch\" (unsupported version: 2); please report an issue"

### ISSUE THREAD

**Issue by BraveY** [golangci/golangci-lint-action#1205]
### Welcome

- [x] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### Description of the problem

In this [action](https://github.com/dragonflyoss/nydus/actions/runs/14010052306/workflow), i got the below errors:
```
Running [/home/runner/golangci-lint-1.61.0-linux-amd64/golangci-lint config path] in [/home/runner/work/nydus/nydus/contrib/nydus-overlayfs] ...
  Running [/home/runner/golangci-lint-1.61.0-linux-amd64/golangci-lint config verify] in [/home/runner/work/nydus/nydus/contrib/nydus-overlayfs] ...
  Running [/home/runner/golangci-lint-1.61.0-linux-amd64/golangci-lint run --path-prefix=contrib/nydus-overlayfs --timeout=10m --verbose] in [/home/runner/work/nydus/nydus/contrib/nydus-overlayfs] ...
  level=info msg="golangci-lint has version 1.61.0 built with go1.23.1 from a1d6c560 on 2024-09-09T17:44:42Z"
  level=info msg="[config_reader] Config search paths: [./ /home/runner/work/nydus/nydus/contrib/nydus-overlayfs /home/runner/work/nydus/nydus/contrib /home/runner/work/nydus/nydus /home/runner/work/nydus /home/runner/work /home/runner /home /]"
  level=info msg="[config_reader] Used config file .golangci.yml"
  level=info msg="[lintersdb] Active 10 linters: [gofmt goimports gosimple govet ineffassign misspell revive staticcheck unconvert unused]"
  level=info msg="[loader] Go packages loading at mode 575 (exports_file|files|imports|types_sizes|compiled_files|name|deps) took 13.067930153s"
  level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 416.777µs"
  level=info msg="[linters_context/goanalysis] analyzers took 4.099965ms with top 10 stages: S1011: 65.021µs, SA1019: 59.852µs, SA1011: 54.161µs, tests: 53.701µs, SA4028: 51.316µs, SA4003: 48.53µs, S1001: 46.216µs, ctrlflow: 44.873µs, SA4030: 44.593µs, lostcancel: 43.682µs"
  level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package goarch: could not load export data: internal error in importing \"internal/goarch\" (unsupported version: 2); please report an issue"
  level=info msg="[runner] processing took 2.207µs with stages: max_same_issues: 311ns, skip_dirs: 230ns, cgo: 181ns, filename_unadjuster: 181ns, identifier_marker: 180ns, nolint: 171ns, invalid_issue: 150ns, skip_files: 140ns, max_from_linter: 91ns, fixer: 51ns, source_code: 50ns, severity-rules: 50ns, diff: 50ns, sort_results: 50ns, exclude: 41ns, uniq_by_line: 40ns, autogenerated_exclude: 40ns, path_prefixer: 40ns, max_per_file_from_linter: 40ns, path_shortener: 40ns, path_prettifier: 40ns, exclude-rules: 40ns"
  level=info msg="[runner] linters took 649.292781ms with stages: goanalysis_metalinter: 649.260411ms"
  level=error msg="Running error: can't run linter goanalysis_metalinter\nbuildir: failed to load package goarch: could not load export data: internal error in importing \"internal/goarch\" (unsupported version: 2); please report an issue"
  level=info msg="Memory: 139 samples, avg is 26.8MB, max is 1[36](https://github.com/dragonflyoss/nydus/actions/runs/14010052306/job/39228697226#step:4:38).2MB"
  level=info msg="Execution took 13.721497491s"
```

### Version of golangci-lint

golangci-lint-1.61.0-linux-amd64

### Version of the GitHub Action

golangci/golangci-lint-action@v6

### Workflow file

<details>

```yml
  contrib-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: contrib/nydusify
          - path: contrib/nydus-overlayfs
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.work'
        cache: false
    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.61
        working-directory: ${{ matrix.path }}
        args: --timeout=10m --verbose
```

</details>

### Golangci-lint configuration

<details>

```yml
<add your file content here>
```

</details>

### Go version

1.24.0

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>
