### ISSUE TITLE
Annotations fail for mono-repo wihout using 'args: --path-prefix='

### ISSUE THREAD

**Issue by HaraldNordgren** [golangci/golangci-lint-action#1228]
### Welcome

- [x] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### Description of the problem

I'm setting up golangci-lint GH action and it works almost. I follow the "Go Workspace Example" from https://github.com/golangci/golangci-lint-action?tab=readme-ov-file#how-to-use, but for me each lint job runs as as step in my regular build job, I have 50+ services/jobs already, so it seemed easiest to do it that way.

![Image](https://github.com/user-attachments/assets/73014f67-3e66-44f3-99be-fd937826f90c)

Issues are successfully reported as issues on the jobs themselves itself, see image above.

But annotations fail to be shown in the "Files changed" tab on the pull request.

I have concluded that the issue is that the `working-directory` though `path-prefix` (https://github.com/golangci/golangci-lint-action/blob/main/src/run.ts#L127) gets added twice the the path that attempts to be sent to GitHub annotations and it rejects it.

By re-running my CI job with debug logging turned on I see that path has a weird structure: ``

One (bad) workaround is to run my job step like this:

```yaml
      - name: Run golangci-lint
        if: always()
        uses: golangci/golangci-lint-action@v7
        with:
          working-directory: ${{ matrix.service }}
          args: --path-prefix= #Adding this to make the annotations work
          version: v2.0
```

However, this has the effect that each CI job runs the linting for all the other services as well. Balooning the time by 10x!

### Version of golangci-lint

v2.0.2

### Version of the GitHub Action

v7

### Workflow file

<details>

```yml
---
name: build-go

on:
  push:
    paths:
      - 'go.mod'
      - 'cmd/**'
      - 'pkg/**'
      - 'hava-pkg/**'
      - 'services/**'
      - '.github/workflows/go.yaml'

jobs:
  gen_build_list:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.gen_list.outputs.services }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 100

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - run: git fetch origin master

      - id: gen_list
        run: echo "${SERVICES}" # Redacted

  build:
    permissions:
      contents: 'write'
      pull-requests: 'write'
      id-token: 'write'
      checks: 'write'

    needs: gen_build_list
    if: needs.gen_build_list.outputs.services != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.gen_build_list.outputs.services) }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: build ${{ matrix.service }}
        env:
          GOPRIVATE: "github.com/dietdoctor/*"
        run: go run ./cmd/hive build ${{ matrix.service }}

      - name: Run golangci-lint
        if: always()
        uses: golangci/golangci-lint-action@v7
        with:
          working-directory: ${{ matrix.service }}
          version: v2.0

```

</details>

### Golangci-lint configuration

<details>

```yml
version: "2"

run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - goconst
    - makezero
    - rowserrcheck
    - sqlclosecheck
    - testifylint
    - unparam
    - whitespace
  exclusions:
    paths:
      - services/ddapi/pkg/schema
      - services/subscriptions
    rules:
      - path: '(^pkg/|^services/users/)'
        linters:
          - bodyclose
          - goconst
          - makezero
          - rowserrcheck
          - sqlclosecheck
          - testifylint
          - unparam
          - whitespace

```

</details>

### Go version

go1.24.2

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>
