### ISSUE TITLE
golangci/golangci-lint-action@v8 does not support all linters

### ISSUE THREAD

**Issue by arjendevos** [golangci/golangci-lint-action#1258]
### Welcome

- [x] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [x] Yes, I've searched similar issues on GitHub and didn't find any.
- [x] Yes, I've included all information below (version, config, etc).

### Description of the problem

I use `golangci-lint has version 2.2.1 built with go1.24.4 from 66496a9 on 2025-06-29T15:57:59Z` locally. 

However I get this error: ` Error: unknown linters: 'embeddedstructfieldcheck', run 'golangci-lint help linters' to see the list of supported linters` while locally it does exists.

### Version of golangci-lint

2.1.1

### Version of the GitHub Action

8

### Workflow file

<details>

```yml
           - name: Lint backend
              uses: golangci/golangci-lint-action@v8
              with:
                working-directory: apps/backend
                version: v2.1.1
                args: --timeout 5m
```

</details>

### Golangci-lint configuration

<details>

```yml
version: "2" # https://golangci-lint.run/usage/configuration/
linters:
  default: fast
  disable: # TODO: these should be enabled
     - cyclop
     - depguard
     - dupl
     - embeddedstructfieldcheck
     - funcorder
     - funlen
     - gochecknoinits
     - gocognit
     - godot
     - godox
     - inamedparam
     - lll
     - misspell
     - mnd
     - nestif
     - nlreturn
     - nolintlint
     - prealloc
     - predeclared
     - tagalign
     - testpackage
     - usestdlibvars
     - whitespace
     - wsl
     - gocyclo
     - maintidx
     - nosprintfhostport

formatters:
  enable:
    # - gci
    - gofmt
    # - gofumpt
    # - goimports
```

</details>

### Go version

1.24

### Code example or link to a public repository

<details>

Code does not matter in this case.

</details>
