### ISSUE TITLE
1.33.0: "File exists" errors when un-taring golangci-lint

### ISSUE THREAD

**Issue by andig** [golangci/golangci-lint-action#135]
I'm using the linter action in https://github.com/andig/evcc/pull/497/checks?check_run_id=1474850871:

Go artefacts are already cached:

    steps:
    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          **/node_modules
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-go-

    ...

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.33
        
This leads to large amount of errors in the action log:

    Installed Go in 79ms
    Requested golangci-lint 'v1.33', using 'v1.33.0', calculation took 226ms
    Installing golangci-lint v1.33.0...
    Downloading https://github.com/golangci/golangci-lint/releases/download/v1.33.0/golangci-lint-1.33.0-linux-amd64.tar.gz ...
    Received 92009212 of 92009212 (100.0%), 146.0 MBs/sec
    Cache Size: ~88 MB (92009212 B)
    /bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/1fe13742-cdde-4fcd-88d4-a1bcad1244b3/cache.tzst -P -C /home/runner/work/evcc/evcc
    /bin/tar xz --warning=no-unknown-keyword -C /home/runner -f /home/runner/work/_temp/11aa6afa-628a-4b5d-94a5-40d55abea5bd
    Error: /bin/tar: ../../../go/pkg/mod/gopkg.in/ini.v1@v1.62.0/ini.go: Cannot open: File exists
    Error: /bin/tar: ../../../go/pkg/mod/gopkg.in/ini.v1@v1.62.0/bench_test.go: Cannot open: File exists
    ...
    Error: /bin/tar: ../../../go/pkg/mod/golang.org/x/mod@v0.3.0/modfile/rule.go: Cannot open: File exists
    Error: /bin/tar: ../../../go/pkg/mod/golang.org/x/mod@v0.3.0/modfile/print.go: Cannot open: File exists
    /bin/tar: Exiting with failure status due to previous errors
    Warning: Tar failed with error: The process '/bin/tar' failed with exit code 2
    Prepared env in 3125ms

**Comment by dahu33** [comment]
I have the same issue.

**Comment by h4yfans** [comment]
Same!

**Comment by phillbaker** [comment]
Perhaps `installLint` should return early if the install path already exists?

https://github.com/golangci/golangci-lint-action/blob/54a84d46fb7183443c869b1b7d0dc34f640fcfd7/src/run.ts#L19

**Comment by nicovogelaar** [comment]
A workaround is to run this before:
```shell
go clean -modcache
```

**Comment by andig** [comment]
Thats not acceptable imho. The expectation of finding a clean modcache is wrong.

**Comment by NomNes** [comment]
I have the same issue, but only on self-hosted runner

**Comment by gabizou** [comment]
I'm running into this issue after having something like this as a run file (using protoc to generate models)
```yaml
name: "golangci-lint report"
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Go
                uses: actions/setup-go@v2
                with:
                    go-version: 1.15
            -   name: Install Protoc
                uses: arduino/setup-protoc@v1
                with:
                    version: '3.14'
            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: |
                        .go/cache
                        ./gen
                    key: ${{ runner.os }}-${{ hashFiles('./go.mod') }}
            -   name: Add protoc to path
                run: |
                    echo "$GOPATH"
                    echo "$GOPATH/bin" >> $GITHUB_PATH
                    echo "$PATH"
                    go get -u github.com/golang/protobuf/protoc-gen-go
            -   name: Setup generated code
                run: |
                    make setup
            -   name: golangci-lint
                uses: golangci/golangci-lint-action@v2
                with:
                    # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
                    version: v1.34
                    args: -v --timeout=5m

```
The trouble is that our makefile does set up  the code generation with both `go generate` and `protoc`. Any advice? I'm struggling to find a happy medium for having code generation and linting in actions.

**Comment by andig** [comment]
It seems the issue has been around for some time and accepted as being an issue with the linter action: linter expects module cache as clean which is not reasonable. Workarounds like cleaning the module cache appear undesirable regarding performance.

Is there anything missing in terms of transparency or input to move this into fixing?

**Comment by SVilgelm** [comment]
The issue should be fixed by #156 , but there is an issue with macOs

**Comment by steebchen** [comment]
Thanks to all fixing this!

**Comment by SVilgelm** [comment]
It's released in v2.4.1

**Comment by andig** [comment]
I'm still seeing these errors using `golangci/golangci-lint-action@v2`. Do I need to upgrade my build in any way?

**Comment by kprav33n** [comment]
I tried v2.4.1 and it doesn't seem to fix the issue for me.

Here is my configuration

```yaml
name: Code sanity
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - wip
  pull_request:
jobs:
  default:
    name: Code sanity
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Install protobuf compiler
        run: sudo apt-get install protobuf-compiler
      - name: Install protobuf and grpc generators
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - name: Generate protobuf and grpc bindings
        run: go generate
      - name: Run linting
        uses: golangci/golangci-lint-action@v2.4.1
        with:
          version: v1.37.1
```

Here is a snippet from the log.

```
Run golangci/golangci-lint-action@v2.4.1
  with:
    version: v1.37.1
    github-token: ***
    only-new-issues: false
    skip-go-installation: false
    skip-pkg-cache: false
    skip-build-cache: false
  env:
    GOROOT: /opt/hostedtoolcache/go/1.15.8/x64
prepare environment
  Finding needed golangci-lint version...
  Setup go stable version spec 1
  Found in cache @ /opt/hostedtoolcache/go/1.16.0/x64
  Added go to the path
  Installing golangci-lint v1.37.1...
  Downloading https://github.com/golangci/golangci-lint/releases/download/v1.37.1/golangci-lint-1.37.1-linux-amd64.tar.gz ...
  Successfully setup go version 1
  go version go1.16 linux/amd64
  
go env
  GO111MODULE=""
  GOARCH="amd64"
  GOBIN=""
  GOCACHE="/home/runner/.cache/go-build"
  GOENV="/home/runner/.config/go/env"
  GOEXE=""
  GOFLAGS=""
  GOHOSTARCH="amd64"
  GOHOSTOS="linux"
  GOINSECURE=""
  GOMODCACHE="/home/runner/go/pkg/mod"
  GONOPROXY=""
  GONOSUMDB=""
  GOOS="linux"
  GOPATH="/home/runner/go"
  GOPRIVATE=""
  GOPROXY="https://proxy.golang.org,direct"
  GOROOT="/opt/hostedtoolcache/go/1.16.0/x64"
  GOSUMDB="sum.golang.org"
  GOTMPDIR=""
  GOTOOLDIR="/opt/hostedtoolcache/go/1.16.0/x64/pkg/tool/linux_amd64"
  GOVCS=""
  GOVERSION="go1.16"
  GCCGO="gccgo"
  AR="ar"
  CC="gcc"
  CXX="g++"
  CGO_ENABLED="1"
  GOMOD="/home/runner/work/mapreduce/mapreduce/go.mod"
  CGO_CFLAGS="-g -O2"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-g -O2"
  CGO_FFLAGS="-g -O2"
  CGO_LDFLAGS="-g -O2"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3333635328=/tmp/go-build -gno-record-gcc-switches"
  
Installed Go in 168ms
/usr/bin/tar xz --overwrite --warning=no-unknown-keyword -C /home/runner -f /home/runner/work/_temp/811fb309-b7a1-454a-a264-8d123d4b2c16
Installed golangci-lint into /home/runner/golangci-lint-1.37.1-linux-amd64/golangci-lint in 798ms
Received 69036137 of 69036137 (100.0%), 73.4 MBs/sec
Cache Size: ~66 MB (69036137 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/e5fbd38b-6100-403b-884c-492880e5f9c7/cache.tzst -P -C /home/runner/work/mapreduce/mapreduce
Error: /usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/integration_test.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/regenerate.bash: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/AUTHORS: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/release.bash: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/.gitignore: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/google.golang.org/protobuf@v1.25.0/go.mod: Cannot open: File exists
```

**Comment by andig** [comment]
Same here using @v2

**Comment by kprav33n** [comment]
As a workaround, I'm forcing the action not to use pkg cache. This solves my issue for now.

```yaml
      - name: Run linting
        uses: golangci/golangci-lint-action@v2.4.1
        with:
          version: v1.38
          skip-go-installation: true
          skip-pkg-cache: true
```
