### ISSUE TITLE
Skip flags aren't working

### ISSUE THREAD

**Issue by painhardcore** [golangci/golangci-lint-action#165]
Config
```
    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.37.0
        skip-go-installation: true
        skip-pkg-cache: true
        skip-build-cache: true
```
Results with:
```
Warning: Unexpected input(s) 'skip-go-installation', 'skip-pkg-cache', 'skip-build-cache', valid inputs are ['version', 'args', 'working-directory', 'github-token', 'only-new-issues']
```

**Comment by vearutop** [comment]
Please try using `v2.4.0`, it worked for me.

```
    - uses: golangci/golangci-lint-action@v2.4.0
      with:
        version: v1.37.0
        skip-go-installation: true
        skip-pkg-cache: true
        skip-build-cache: true
```
