### ISSUE TITLE
Downloads linux binary for windows build

### ISSUE THREAD

**Issue by sbellus** [golangci/golangci-lint-action#17]
.yaml file 
```
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include: 
        - os: windows-latest
          PACKAGE: windows
        - os: ubuntu-latest
          PACKAGE: ubuntu
          
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.27
```
On windows I get following error
```
  Running [D:\a\_temp\746ef7d1-0c3f-4a2d-8be1-22d2958a64cc\golangci-lint-1.27.0-linux-amd64\golangci-lint run --out-format=github-actions] ...
  'D:\a\_temp\746ef7d1-0c3f-4a2d-8be1-22d2958a64cc\golangci-lint-1.27.0-linux-amd64\golangci-lint' is not recognized as an internal or external command,
  operable program or batch file.
```
