### ISSUE TITLE
The "rebuild" of v2 broke github actions on my repo

### ISSUE THREAD

**Issue by dtracers** [golangci/golangci-lint-action#172]
```
Failed to run: Error: ENOENT: no such file or directory, open 'go.mod', Error: ENOENT: no such file or directory, open 'go.mod'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at getRequestedLintVersion (/home/runner/work/_actions/golangci/golangci-lint-action/v2/dist/run/index.js:2286:28)
    at Object.<anonymous> (/home/runner/work/_actions/golangci/golangci-lint-action/v2/dist/run/index.js:2323:32)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/golangci/golangci-lint-action/v2/dist/run/index.js:2233:71
    at new Promise (<anonymous>)
    at module.exports.__awaiter (/home/runner/work/_actions/golangci/golangci-lint-action/v2/dist/run/index.js:2229:12)
    at Object.findLintVersion (/home/runner/work/_actions/golangci/golangci-lint-action/v2/dist/run/index.js:2321:12)
    at /home/runner/work/_actions/golangci/golangci-lint-action/v2/dist/run/index.js:6724:47
Error: ENOENT: no such file or directory, open 'go.mod'
```

It was working yesterday but now is broken on changed repos.

Github actions setup:

```
      # LINTING STARTS HERE
      - name: Run golangci-lint Code Performance
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: ${{ matrix.lintfolder }}
          args: --issues-exit-code=0 --tests=false --skip-dirs=test -E=exportloopref -E=interfacer -E=maligned -E=prealloc
```
