### ISSUE TITLE
Make download URL for golangci-lint configurable

### ISSUE THREAD

**Issue by sspaink** [golangci/golangci-lint-action#201]
I am interested in using this Github Action along with a [private linter](https://golangci-lint.run/contributing/new-linters/#how-to-add-a-private-linter-to-golangci-lint) but this isn't possible at the moment because the release builds use CGO_ENABLED=0, while CGO_ENABLED=1 is required to use plugins (related issue: https://github.com/golangci/golangci-lint/issues/1276)

The best solution I can come up with is to make the download URL configurable, where if a custom URL is set that is what the function [getAssestURL](https://github.com/golangci/golangci-lint-action/blob/master/src/install.ts#L11) returns. This would let users build and deploy a version of golangci-lint with CGO_ENABLED=1 and host it somewhere, and still use this github action.

I'd be happy to make a pr to address this, but would like feedback to make sure this is the correct approach? because from the issue linked above it seems this is currently a blocker to use private linters.

**Comment by thebeline** [comment]
Not sure if this addresses your issue or not (as I don't fully understand it), but if you are looking to set `go env` variables (again, I may be off) or what have you, the following may offer some guidance:

```
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: GolangCI INIT
        uses: golangci/golangci-lint-action@master
        with:
          version: v1.39.0
          # the following causes golangci-init to do nothing, so all it does is install golang
          args: --version
      - name: Configure Golang ENV
        run: go env -w GOFLAGS=-tags=gtk_3_22,glib_2_58,pango_1_42,gdk_pixbuf_2_38
        # or do whatever
      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@master
        with:
          version: v1.39.0
          skip-go-installation: true
```
