### ISSUE TITLE
Why the execution of golangci-lint takes so much time

### ISSUE THREAD

**Issue by Moser-ss** [golangci/golangci-lint-action#297]
In the documentation, it says the execution of golangci-lint could take 1s or 35s without cache, but in my project, I am getting a bigger time to execute the command.
For example, I had a run that took 110629ms, and it is a small project. In my machine normally took 4s (based on the output of the time command) 
In the GitHub action I am using the same setup we have in the documentation

Job definition
```yaml
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --timeout 3m0s
```

Job output
```shell
Run golangci/golangci-lint-action@v2
prepare environment
go env
Installed Go in 230ms
Requested golangci-lint 'v1.29', using 'v1.29.0', calculation took 261ms
Installing golangci-lint v1.29.0...
Downloading https://github.com/golangci/golangci-lint/releases/download/v1.29.0/golangci-lint-1.29.0-linux-amd64.tar.gz ...
Cache not found for input keys: golangci-lint.cache-2690-bc8b7dd79789a0f804ae3b455ac3675f98516b1a, golangci-lint.cache-2690-, golangci-lint.cache-
/usr/bin/tar xz --overwrite --warning=no-unknown-keyword -C /home/runner -f /home/runner/work/_temp/2680cbd8-7cef-4ae9-b3f8-76eda97557b9
Installed golangci-lint into /home/runner/golangci-lint-1.29.0-linux-amd64/golangci-lint in 693ms
Prepared env in 957ms

run golangci-lint
  Running [/home/runner/golangci-lint-1.29.0-linux-amd64/golangci-lint run --out-format=github-actions --timeout 3m0s] in [] ...
  golangci-lint found no issues
  Ran golangci-lint in 110629ms

```

Local machine output
```shell
time golangci-lint run --out-format=github-actions --timeout 3m0s
golangci-lint run --out-format=github-actions --timeout 3m0s  4.34s user 5.27s system 399% cpu 2.404 total
```

**Comment by Hongbo-Miao** [comment]
My golangci-lint action recently 50% time failed because of timeout issue since a week ago. Mine is a small project too.

Here is when it goes well
https://github.com/Hongbo-Miao/hongbomiao.com/runs/3297080244?check_suite_focus=true
```sh
  Running [/home/runner/golangci-lint-1.40.1-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=api-go] in [/home/runner/work/hongbomiao.com/hongbomiao.com/api-go] ...
  golangci-lint found no issues
  Ran golangci-lint in 6029ms
```

And here is when it goes wrong
https://github.com/Hongbo-Miao/hongbomiao.com/runs/3298464932?check_suite_focus=true
```sh
  Running [/home/runner/golangci-lint-1.40.1-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=api-go] in [/home/runner/work/hongbomiao.com/hongbomiao.com/api-go] ...
  level=error msg="Timeout exceeded: try increasing it by passing --timeout option"
  
  Error: golangci-lint exit with code 4
  Ran golangci-lint in 71047ms
```

As you see, both runs happen recently on same small project, however, when golangci-lint goes wrong, it can take a long time.

**Comment by ngfgrant** [comment]
We are also increasingly seeing this behaviour in our builds. Is there anything I can do to help?

**Comment by SVilgelm** [comment]
It really depends on the number of enabled linters. Some linters requires whole project to be loaded, other linters are just slow by their nature.
I would recommend to add `--verbose` flag to see what linters takes the most time and try to adjust a configuration or disable those linters.
```yaml
lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          skip-go-installation: true
          version: latest
          args: --timeout 3m --verbose
```
