### ISSUE TITLE
Why does golangci action updates golang version ?

### ISSUE THREAD

**Issue by antonincms** [golangci/golangci-lint-action#334]
I am not sure if this is a bug or a feature, but with the following workflow : 

```
# Checks are executed on each push

name: Checks

on: ["push"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2

      - run: go version
      - run: which go

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.32
          args: --timeout 5m

      - run: go version
      - run: which go
```

It appears that running the action update the current version of go : 
![image](https://user-images.githubusercontent.com/9219052/133075801-a07773e0-9bc1-498e-86ed-bab194abf376.png)

It is problematic for our workflow and I was wondering if it was a configuration issue, a bug or if it was like that (in which case I would need to isolate this action in its own job).
