### ISSUE TITLE
How does configuration file work in monorepo?

### ISSUE THREAD

**Issue by hiromaily** [golangci/golangci-lint-action#360]
Configuration file looks not working when in monorepo.
Though I found similar issue [Configuration file](https://github.com/golangci/golangci-lint-action/issues/285),
multiple modules are contained in repository and each module has own configuration file (.golangci.yml). However it seems not working because disabled linter worked in directory which doesn't enable in .golangci.yml.

In the below case, each directory `dir1/pkg2`, `dir2/pkg2` has different `.golangci.yml`
```
      - name: linter module1
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          working-directory: dir1/pkg2
      - name: linter module2
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          working-directory: dir2/pkg2
```
