### ISSUE TITLE
How To Check If Go Fmt Was Run?

### ISSUE THREAD

**Issue by KumarAshish155** [golangci/golangci-lint-action#361]
We are unable to detect if "gofmt" was executed. I read the doc that is disabled by default. How to enable it on github actions?

**Comment by bombsimon** [comment]
Create a file named `golangci.yml` in the root of your repository, add (at least) the following to enable `gofmt`:

```yaml
linters:
  enable:
    - gofmt
 ```

This will be picked up by the action and run the check to see if the files are gofmt-ed. Full details about configuration available in the `golangci.yml` file can be found [here](https://golangci-lint.run/usage/configuration/).

**Comment by SVilgelm** [comment]
you can add the `--verbose` parameter
```yaml
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --verbose
```

then check the output, `golangci-lint` will report all linters that are enabled
