### ISSUE TITLE
Discussion: get rid of setup-go dep, due to outdated code and inability to update any dependencies

### ISSUE THREAD

**Issue by SVilgelm** [golangci/golangci-lint-action#365]
Hello, I would like to ask everyone in @golangci/team and  @golangci/core-team about you opinion in removing the setup-go as direct dependency.

Now we are stuck in upgrading any dependencies, fixing any vulns, due to inability to build the setup-go package.

So if we remove it then we will need to explicitly install go, like
```yaml
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2  # <-- here
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
```

of course it will require to bump v3.

**Comment by ldez** [comment]
Hello,

The problem is that Go is required to run golangci-lint.

Then we have to provide something to inform the users.

**Comment by SVilgelm** [comment]
> The problem is that Go is required to run golangci-lint.

sure, we can check if go is not installed, then just fail the step with an error message

**Comment by magnetikonline** [comment]
I'm explicitly installing Golang in lint workflows anyway, so this works for me. 

To avoid excessive boilerplate, I've authored a composite action (simple yaml based action) - which can now include other actions in their steps as of a few weeks ago (previously only shell steps were possible as steps).

Using a composite action I can execute both setup-go and then golangci-lint actions together and reference this as a one liner from other workflows. 

Maybe we can offer up a simple composite action under this organisation, offering users this internal use path - and keeping setup-go out of any deps? Seems like the best of both worlds?

**Comment by SVilgelm** [comment]
> I'm explicitly installing Golang in lint workflows anyway, so this works for me.

I'm doing it as well

> composite action

I think this is a good idea

**Comment by magnetikonline** [comment]
Just to circle back @SVilgelm - this is how I'm handing it in a small composite action. Something I think could be offered up in the https://github.com/golangci org.

https://github.com/flipgroup/action-golang-with-lint

Of course a more complete version could pass over all allowed lint action arguments. Note I'm having to set `skip-go-installation: true` - it's not critical, but stops the action doing unrequired work/saves some runtime.

**Comment by meling** [comment]
Not sure if my problem is related to this issue, but I got this error:
```
 Error: ParseFS not declared by package template (typecheck)
```
Presumably this is because `ubuntu-latest` has Go version lower than 1.16. Do I have to install Go 1.16 or later using `actions/setup-go@v2`, as this issue is seemingly suggesting to drop?

Ergonomically, it would be great if `golangci-lint` would pick a Go version at least equal to or higher than the one specified in `go.mod`. IMO, there is no reason to run `golangci-lint` using a lower version than the one specified in `go.mod`. I'm not sure what is the right approach for picking the Go versions to use though without the `actions/setup-go@v2`??

Here is the yml:
```yml
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
          args: --disable errcheck --timeout 5m
          only-new-issues: true
```
