### ISSUE TITLE
Respect the default working-directory of a job

### ISSUE THREAD

**Issue by loshz** [golangci/golangci-lint-action#369]
When setting the default working-directory of a job, `golangci-lint-action` does not respect this parameter.

For example, I have the following project structure:
```bash
├── .github
│   └── workflows
│       └── ci.yml
├── some_dir
│   ├── .golangci.yml
│   ├── go.mod
│   ├── main.go
│   └── README.md
└── README.md
```
And a configured GitHub actions job:
```yaml
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: some_dir
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
```

To which I receive the following error:
```
Running [/home/runner/golangci-lint-1.43.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
level=error msg="Running error: context loading failed: no go files to analyze"
```

This is because `golangci-lint run` is still being ran from the root directory. If I pass the `working-directory` arg to the GH action, it works as expected:
```yaml
- uses: golangci/golangci-lint-action@v2
  with:
    version: v1.43
    working-directory: some_dir
```

As I can see the `--path-prefix` flag being passed:
```
 Running [/home/runner/golangci-lint-1.43.0-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=some_dir] in [/home/runner/work/some_proj/some_dir] ...
  golangci-lint found no issues
  Ran golangci-lint in 3177ms
```
