### ISSUE TITLE
Does not work with dependencies from private repo (typecheck)

### ISSUE THREAD

**Issue by nerijuszaniauskas** [golangci/golangci-lint-action#419]
Action is not working with dependencies  from private repos (I guess this is the cause).

Error: `Error: a.Redirect undefined (type *authorizeController has no field or method Redirect) (typecheck)`

Action:
```
...
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
...
```

Struct:
```
type authorizeController struct {
	appHttp.BaseController
```

`appHttp` is from private repo on GitHub, and `BaseController` is where func `Redirect` is defined.  When I run:
* `golangci-lint run` locally, it works ✅ 
* `golangci-lint run` in own pipeline/workflow/action, it works ✅ 
* with action `golangci/golangci-lint-action@v3.1.0` fails with error above 🟥 

I guess it is because it can not download dependencies.

Is there a way to solve this and use this action?
Or disable `typecheck` (as I read it is not [possible)](https://github.com/golangci/golangci-lint-action/issues/206)?

**Comment by SVilgelm** [comment]
Here is really good blog post about the usage of the dependencies from the private repositories: https://medium.com/cloud-native-the-gathering/go-modules-with-private-git-repositories-dfe795068db4

**Comment by luisdavim** [comment]
@SVilgelm do you mean that this is a confirmation issue on our end?

**Comment by SVilgelm** [comment]
I cannot say so for 100%, that the issue on your side. But in most similar cases yes, the action is not an issue here.
I don't know how you run it locally or how this option `golangci-lint run in own pipeline/workflow/action, it works` is configured. So without additional details, I'm pretty sure that the issue because of n access to private repo.

The `typecheck` is not a real linter, it is kind of compilation error. Instead of running the action, create a unit test that creates an object of the authorizeController struct and run that unit test in same workflow and you will see the real error.
or try `go mod download`

**Comment by luisdavim** [comment]
I've updated my config to setup private repos and now I get the following:

```
can't run linter goanalysis_metalinter: inspect: failed to load package : could not load export data: no export data for ...
```

This is my config:

```yaml
# Check for every push

name: Lint

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!main"
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: "github.com/sendoso/*"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3

      - run: git config --global url.https://$GITHUB_TOKEN:x-oauth-basic@github.com/.insteadOf https://github.com/
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45
          args: --timeout 5m

      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@v2
```
