### ISSUE TITLE
"related information" entries persist in cache after fixing root causes

### ISSUE THREAD

**Issue by estesp** [golangci/golangci-lint-action#420]
Recently I was fixing issues found by golangci-lint after updating `go.mod` in a PR for a dependency update.

The PR continued to fail CI even after fixing the **staticcheck** issues for a specific platform (in the end I had to use `// nolint:staticcheck` because we run lint across 3 architecture/OS platforms, and 1 of them had an "unsupported feature" which meant a platform-generic Go file that checks a return got flagged by staticcheck as "never returns a nil value", which is true on that one platform.

Regardless, I assumed that CI would pass after marking these as `nolint:staticcheck`. The specific core errors did go away, but the ["related information" entries](https://github.com/containerd/containerd/runs/5593013033?check_suite_focus=true) appear to persist in the cache and therefore continue to mark this step as a failed step in CI.

I had to workaround it by adding `skip-cache: true` to our golangci-lint stanza to generate a new cache. I assume I could now remove it given those entries are invalidated now.

I believe this is a bug, but I don't know specifically how the cache works in line with the output from golangci-lint. Maybe it is hard to correlate the "related information" to the problem being solved, but if that can't be done then it may be hard to ever use cache as fixing the root golangci-lint flagged issue will never invalidate the "related information" entries.

**Comment by aramprice** [comment]
Retried with a different branch and a smaller change, and got a similar issue. Linter flags deleted content as an error:
<img width="1122" height="747" alt="Image" src="https://github.com/user-attachments/assets/f0e64036-fc83-47e9-8baa-859cb26020f9" />

https://github.com/cloudfoundry/bosh-azure-storage-cli/pull/27

**Comment by hu3bi** [comment]
Even with `skip-cache` I get this issue in ci:

`//nolint:revive is unused for linter "revive" (nolintlint)`

And the weird part is, I can just rerun it, and it usually goes away the 2nd time, without any changes. Sometimes it succeeds on the first run and the most it took me were 4 runs.


Rerunning successful builds can start to fail with that issue.

This is my config:
```yml
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          skip-cache: true
```


Locally this issue always goes away after `golangci-lint cache clean`.
Maybe the `setup-go` action restores a cache.
