### ISSUE TITLE
Running error: buildir: failed to load package goarch: could not load export data

### ISSUE THREAD

**Issue by wonderflow** [golangci/golangci-lint-action#434]
It caused error running golangci lint action https://github.com/oam-dev/kubevela/runs/5775307395?check_suite_focus=true

It just happened last night.

My environment:

```
Run golangci/golangci-lint-action@v2
  with:
    version: v1.3.8
    github-token: ***
    only-new-issues: false
    skip-go-installation: false
    skip-pkg-cache: false
    skip-build-cache: false
  env:
    GO_VERSION: 1.17
    GOLANGCI_VERSION: v1.38
    KIND_VERSION: v0.7.0
prepare environment
```

The error message：

```
  level=warning msg="[runner] Can't run linter unused: buildir: failed to load package goarch: could not load export data: cannot import \"internal/goarch\" (unknown iexport format version 2), export data is newer version - update tool"
  level=error msg="Running error: buildir: failed to load package goarch: could not load export data: cannot import \"internal/goarch\" (unknown iexport format version 2), export data is newer version - update tool"
```

Are there any solution for this?

**Comment by segsalerty2013** [comment]
Similar issue here. Anyone has solution to this?

**Comment by MrWormHole** [comment]
I have solved this issue, you gotta add skip installation set to true, they messed up all the pipelines with making installation implicit

**Comment by MrWormHole** [comment]
@SVilgelm thanks!

**Comment by jessesuen** [comment]
We're hitting this as well. Had to keep `setup-go` at 1.17 in order get this to work (despite having the build of our actual binaries in go 1.18 in another job).

```yaml
jobs:
  lint-go:
    name: Lint Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.8'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.38.0
```
