### ISSUE TITLE
Error using golang 1.18

### ISSUE THREAD

**Issue by rodoufu** [golangci/golangci-lint-action#442]
I'm getting the error:
```sh
Installed golangci-lint into /home/runner/golangci-lint-1.43.0-linux-amd64/golangci-lint in 458ms
Prepared env in 606ms

run golangci-lint
  Running [/home/runner/golangci-lint-1.43.0-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
  
  goroutine 1 [running]:
  github.com/go-critic/go-critic/checkers.init.9()
  	github.com/go-critic/go-critic@v0.6.1/checkers/checkers.go:58 +0x4b4
  
  Error: golangci-lint exit with code 2
  Ran golangci-lint in 13383ms
```

Which is a known issue for `golangci-lint` with golang v1.18.0 https://github.com/golangci/golangci-lint/issues/2374

My GitHub action file is:
```yaml
name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
```

I've also tried to use:
```yaml
name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.17.x]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
```

But both are failing, what can I do in that case?

**Comment by SVilgelm** [comment]
`v2` of the action is used to install the lates stable Go automatically, to skip the installation of go and use the pre installed we had to use `skip-go-installation` parameter.
But recently we released `v3` of the action, it does not install go and uses only pre-installed go.
in you case change `uses: golangci/golangci-lint-action@v2` to `uses: golangci/golangci-lint-action@v3`  in second example

**Comment by 3100** [comment]
The matrix keys do not seem to match, would correcting that solve the problem?

```
    strategy:
      matrix:
        go-version: [1.17.x]
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
```

**Comment by rhcarvalho** [comment]
I ran into a similar problem trying to update a repo to use **Go 1.19** and **`golangci-lint` v1.47.3**, the latest versions as of writing.

The latest released binary of `golangci-lint` was built with Go 1.18 and doesn't work with Go 1.19. This action always downloads released binaries.

## Workaround

I worked around the issue by building `golangci-lint` from source using the same Go version that I'm targeting.

Example: https://gist.github.com/rhcarvalho/9f2ae0742f5496271526b3e572da1d34

```yaml
# .github/workflows/test.yml
# ...
jobs:
  # ...
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          # go-version: 1.19
          go-version-file: go.mod
          # The builtin cache feature ensures that installing golangci-lint
          # is consistently fast.
          cache: true
          cache-dependency-path: go.sum
      - name: Install golangci-lint
        # Install golangci-lint from source instead of using
        # golangci-lint-action to ensure the golangci-lint binary is built with
        # the same Go version we're targeting.
        # Avoids incompatibility issues such as:
        # - https://github.com/golangci/golangci-lint/issues/2922
        # - https://github.com/golangci/golangci-lint/issues/2673
        # - https://github.com/golangci/golangci-lint-action/issues/442
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3
      - name: Run golangci-lint
        run: golangci-lint run --version --verbose --out-format=github-actions
```

I hope the above can help others :heart:
