### ISSUE TITLE
[Error] Can't run linter goanalysis_metalinter: buildir

### ISSUE THREAD

**Issue by hiromaily** [golangci/golangci-lint-action#448]
I found error suddenly due to [go1.18 issue](https://github.com/golangci/golangci-lint-action/issues/442)
Then I tried to change configuration followed by the above issue, another error as title happened after configuration changed. 

Errors are
```
run golangci-lint
  Running [/home/runner/golangci-lint-1.45.2-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=cmds/alpha] in [/home/runner/work/org/my-repo/cmds/alpha] ...
  level=warning msg="[runner] Can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"io/fs\""
  level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"io/fs\"\n\n"
```

configuration
```
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golangci-lint for alpha cmds
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          working-directory: cmds/alpha
```

difference from most of common use is I'm using monorepo and I use `working-directory`. I'm not sure `.golangcli.yaml` stored in root directory is used properly in this version, thought it used to be work.
