### ISSUE TITLE
No line numbers shown

### ISSUE THREAD

**Issue by Tim-W** [golangci/golangci-lint-action#485]
We use golangci-lint in Github Actions. When the linter fails it does not return the respective lines in the code where the error happened; it only shows the error message and error code.

For example:

```
2022-05-31T14:47:53.9772916Z ##[error]SA9003: empty branch (staticcheck)
2022-05-31T14:47:53.9773979Z 
2022-05-31T14:47:53.9774939Z ##[error]issues found
2022-05-31T14:47:53.9775970Z Ran golangci-lint in 45497ms
```

Our Github Actions configuration:
```
jobs:
  lint-go:
    name: Lint Go code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Set up Github'
        run: |
          git config --global url."https://blocklabbot:${{ secrets.BOT_ACCESS_TOKEN }}@github.com".insteadOf "https://github.com"
      - name: 'Set up Go'
        uses: 'actions/setup-go@v3'
        with:
          go-version: '1.17'
      - name: 'install goimports'
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
      - name: 'Generate code'
        working-directory: ./api
        run: |
          ./scripts/generate.sh 
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          working-directory: ./backend
          args: --timeout 5m
```

**Comment by egtann** [comment]
I found a fix for this from another issue, which is to do this:

```
- name: Run golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: v1.47.0
                  args: "--out-${NO_FUTURE}format colored-line-number"

```

That at least shows line numbers. Now in my case, the line numbers are wrong, so my hunt for the next solution continues. Best of luck. :+1:
