### ISSUE TITLE
action times out on latest golangci-lint version

### ISSUE THREAD

**Issue by pauleibye** [golangci/golangci-lint-action#519]
Golangci-lint just had a new release, 1.47.0, which broke our lint action. The action would spin and timeout when running the golangci-lint command with or without args. 

Example log where the action would hang:
```  Running [/home/runner/golangci-lint-1.47.0-linux-amd64/golangci-lint run --out-format=github-actions --new-from-patch=/tmp/tmp-1669-7BzhRHngF7zi/pull.patch --new=false --new-from-rev=] in [] ... ```

Downgrading the golangci-lint version to 1.46.2 fixed the action for us.

**Comment by iwata** [comment]
I'm having the same problem too.

**Comment by sbueringer** [comment]
I have the same issue.

Not sure if it's specific to my case but when I run the action locally with https://github.com/nektos/act I can reproduce the issue. When I exec into the action and run golangci-lint I run into the following panic:
```
docker exec -it 13d3 /bin/bash
root@sbuerin:/home/sbuerin/code/src/sigs.k8s.io/cluster-api# /root/golangci-lint-1.47.0-linux-amd64/golangci-lint
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
        github.com/go-critic/go-critic@v0.6.3/checkers/embedded_rules.go:47 +0x4b4
```

(The binary seems to just panic in general, independent of in which folder it is called)

**Comment by ldez** [comment]
If you have the same kind of problem, I need:
- your Go version
- your golangci-lint configuration
- the action configuration
- a public repo (if possible)

**Comment by sbueringer** [comment]
* Go 1.17.11
* https://github.com/kubernetes-sigs/cluster-api/blob/5d60581784610d7c7c8350258740f7fab5aa570b/.golangci.yml
* https://github.com/kubernetes-sigs/cluster-api/blob/5d60581784610d7c7c8350258740f7fab5aa570b/.github/workflows/golangci-lint.yml
* https://github.com/sbueringer/cluster-api/tree/pr-bump-golangci-lint

I could reproduce by:
* checking out this PR: https://github.com/kubernetes-sigs/cluster-api/pull/6943
* Running `act -j golangci` (https://github.com/nektos/act)

**Comment by TenSt** [comment]
@ldez, here it is:
- Go 1.18.x
- we use the default one
- job config:
```yml
go-lint:
  name: Lint Go Applications
  if: needs.vars.outputs.go_changes == 'true'
  runs-on: ubuntu-latest
  needs:
    - vars

  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: "1.18.x"
        cache: true
        cache-dependency-path: go/go.sum

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3.2.0
      with:
        working-directory: go
        version: latest
        args: --timeout 5m
```
- the repo is private, so I can't share
