### ISSUE TITLE
`only-new-issues` does not seem to work on my setup

### ISSUE THREAD

**Issue by EtienneM** [golangci/golangci-lint-action#531]
When I execute my GitHub Action workflow, all offenses are shown.

It might be related to the content of this PR: https://github.com/golangci/golangci-lint-action/pull/520

My GitHub Action configuration file looks like:

```yml
on:
  push:

permissions:
  contents: read
  # allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  linter:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          check-latest: true
      - uses: golangci/golangci-lint-action@v3
        with:
          only-new-issues: true
```
