### ISSUE TITLE
Go 1.18.4 and golangci 1.48: "Error: File is not `gofmt`-ed with `-s` (gofmt)"

### ISSUE THREAD

**Issue by davidwarshaw** [golangci/golangci-lint-action#535]
Github actions pulling `golangci-lint` 1.48 result in the error:
```
run golangci-lint
  Running [/home/runner/golangci-lint-1.48.0-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=mydir] in [/home/runner/work/mydir] ...
  Error: File is not `gofmt`-ed with `-s` (gofmt)
  Error: File is not `gofmt`-ed with `-s` (gofmt)
  Error: File is not `gofmt`-ed with `-s` (gofmt)
  
  Error: issues found
  Ran golangci-lint in 11686ms
```
With these settings:
```
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18"
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ${{ matrix.dir }}
```
Golang setup:
```
Run actions/setup-go@v3
Setup go version spec ^1.18
Found in cache @ /opt/hostedtoolcache/go/1.1[8](https://github.com/myorg/mydir/runs/7695399646?check_suite_focus=true#step:3:9).4/x64
Added go to the path
Successfully set up Go version ^1.18
go version go1.18.4 linux/amd64
```
Rolling back to `golangci-lint` 1.47.3 resolves the issue:
```
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18"
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ${{ matrix.dir }}
          version: v1.47.3
```
Resolved:
```
run golangci-lint
  Running [/home/runner/golangci-lint-1.47.3-linux-amd64/golangci-lint run --out-format=github-actions --path-prefix=mydir] in [/home/runner/work/mydir] ...
  golangci-lint found no issues
  Ran golangci-lint in 11821ms
```
