### ISSUE TITLE
Go 1.19: panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

### ISSUE THREAD

**Issue by andig** [golangci/golangci-lint-action#545]
Running 

```
brew info golangci-lint
golangci-lint: stable 1.48.0 (bottled), HEAD
```

gives 

```
golangci-lint version
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
	/Users/andig/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/embedded_rules.go:47 +0x494
```

Config is very simple:

```
run:
  go: 1.18
issues:
  exclude:
    - .regActualCurrent. is unused
    - "`routeLogger` is unused"
linters-settings:
  staticcheck:
    checks:
      - "-SA1019"
```

I'm seing this both locally and on CI (https://github.com/evcc-io/evcc/runs/7754090278?check_suite_focus=true)

**Comment by andig** [comment]
Looks like I'm hitting https://github.com/go-critic/go-critic/issues/1210 on Go 1.19. I guess disabling go-critic is the only option right now?

**Comment by andig** [comment]
Sorry, didn't even hit the right repo...

**Comment by rfay** [comment]
Seems to fix for me by updating to latest golangci-lint,
```yaml
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.48
```
