### ISSUE TITLE
Golangci-lint exit with code 137

### ISSUE THREAD

**Issue by idanl21** [golangci/golangci-lint-action#552]
Hey!
I'm running your GitHub lint action that worked great! but now somehow I started to get that `golangci-lint exit with code 137` error that was caused by Out Of Mem error.
My conf 

          version: v1.45
          working-directory: opensearch-operator
          args: --timeout=6m --skip-dirs="(^|/)responses($|/)"

**Comment by matzew** [comment]
We notice the same:

```
Killed
  
  Error: golangci-lint exit with code 137
```

**Comment by matzew** [comment]
```
golangci/golangci-lint-action@v3
```

seems _not_ to have this issue

**Comment by ldez** [comment]
Hello, the context of this issue is not clear, can you provide more information (Go version, action version, etc.)?

**Comment by karl-johan-grahn** [comment]
We also started getting this out of nowhere

**Comment by marcus-vw** [comment]
We have been facing the same issue, even with `golangci-lint-action@v3`.
Our workflow failed when we used `golangci/golangci-lint-action@v3` with `golangci-lint` version `1.50.1`. We could fix the workflow by using `golangci-lint-1.51.0`. The action was changed as seen below:

```
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.0  # use 1.51.0 instead of v1.50.1
          args: --timeout 10m
          skip-pkg-cache: true  # don't cache or restore ~/go/pkg.
          skip-build-cache: true # don't cache or restore ~/.cache/go-build
```

**Comment by derekwilling** [comment]
I am still  seeing this issue with the following:
```
level=info msg="[lintersdb] Active 16 linters: [errcheck errorlint gci gocritic godot gosec gosimple govet ineffassign misspell nonamedreturns staticcheck typecheck unconvert unused whitespace]"
  level=info msg="[loader] Go packages loading at mode 575 (imports|name|exports_file|deps|files|types_sizes|compiled_files) took 2m43.333695121s"
  level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 1.349223312s"
  Killed
  
  Error: golangci-lint exit with code 137
  Ran golangci-lint in 48[39](https://github.com/GannettDigital/content-api-sports2/actions/runs/6332224403/job/17198290823?pr=371#step:9:41)37ms
```

The action is defined: 
```
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --verbose --timeout 15m --out-${NO_FUTURE}format colored-line-number # https://github.com/golangci/golangci-lint-action/issues/119
          only-new-issues: true
          skip-pkg-cache: true
          skip-build-cache: true
```

**Comment by ldez** [comment]
This issue seems related to the fact of using a golangci-lint version that does not support the Go version used in your CI.

- v1.56.0 -> go <= 1.22
- v1.54.0 -> go <= 1.21
- v1.51.0 -> go <= 1.20
- v1.48.0 -> go <= 1.19
- v1.45.0 -> go <= 1.18

**Comment by JFDValente** [comment]
I just updated my project to go 1.23, and I got this problem, which version do you recommend I use to solve it?

**Comment by ldez** [comment]
https://golangci-lint.run/welcome/faq/#which-go-versions-are-supported

Basically, it's because you are using a golangci-lint binary that is not compiled with go1.23.

The official binaries are compiled with go1.23 since v1.60.0.

To check that:
```console
$ golangci-lint version
golangci-lint has version 1.61.0 built with go1.23.1 from a1d6c560 on 2024-09-09T17:44:42Z
```

**Comment by zhangyangyu** [comment]
I am using go 1.24 and golangci-lint 1.64.7(the latest) and could still get the error. Seems it needs lots of memory and OOM. So I add `GOMEMLIMIT` to solve it.
```
- name: golangci lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.7
          args: --verbose
          skip-cache: true
        env:
          GOMEMLIMIT: "6GiB"
```
`6GiB` for GitHub Linux runner has a memory cap 7GiB.
