### ISSUE TITLE
`.golangci.yaml` doesn't seem to be picked up on Windows

### ISSUE THREAD

**Issue by itaranto** [golangci/golangci-lint-action#583]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

The following [job](https://github.com/itaranto/efm-langserver/blob/replace-golint-with-revive/.github/workflows/ci.yml) fails **only** on Windows due to already ignored linter errors.

### Version of golangci-lint

v1.49.0

### Version of the GitHub Action

v3.2.0

### Workflow file

```yaml
name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49
      - name: Test
        run: make test
```

### Go version

v1.19.2

### Code example or link to a public repository

https://github.com/itaranto/efm-langserver/blob/replace-golint-with-revive/.github/workflows/ci.yml
https://github.com/mattn/efm-langserver/pull/231
