### ISSUE TITLE
save-state and save-output are deprecated

### ISSUE THREAD

**Issue by david-gang** [golangci/golangci-lint-action#589]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

I am getting warnings in github actions.

>golangci
>The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I looked where save-state is used and it looks like you call the core library.

So i searched for the release notes and look like the latest core version (1.10) solves it by using the new environment variables.

https://github.com/actions/toolkit/blob/192c26f865db0bb700aa0a40d193d08b57123949/packages/core/RELEASES.md

### Version of golangci-lint

3.0.5

### Version of the GitHub Action

2.298.2 (Hosted)

### Workflow file

```
 name: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=5m
```

### Go version

1.18

### Code example or link to a public repository

irrelevant
