### ISSUE TITLE
How can i get more detail infos in the golang-lint-action

### ISSUE THREAD

**Issue by jnan806** [golangci/golangci-lint-action#618]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

the logs is too few, and i cannot judge what the problem in the logs.

How can i get more detail infos in the golang-lint-action

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/43714056/205858544-7a39e6b5-7a1d-4fcf-b096-42192ee645d2.png">

In local, if i exec the command directly , it will print the detail infos, like following:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/43714056/206089751-f096f939-d8e6-49b2-bda1-948c8070432e.png">

### Version of golangci-lint

latest

### Version of the GitHub Action

golangci/golangci-lint-action@v3

### Workflow file

```
jobs:

  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Golangci Lint
      # https://golangci-lint.run/
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
```

### Go version

1.18

### Code example or link to a public repository

https://github.com/opensergo/opensergo-go-sdk/actions/runs/3627078730/jobs/6116638569

`.golangci.yml`

```go
# Options for analysis running.
run:
  # vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  skip-dirs:
    - pkg/proto
    - samples
    - pkg/common/logging/samples
  skip-files:
    - ".*\\.pb\\.go$"
# output configuration options
output:
  format: colored-line-number
# Refer to https://golangci-lint.run/usage/linters
linters-settings:
  govet:
    # Disable analyzers by name.
    # Run `go tool vet help` to see all analyzers.
    disable:
      - stdmethods
linters:
  disable-all: true
  enable:
    - goimports
    - gofmt
    - misspell
    - govet
    - ineffassign
    - staticcheck
issues:
  exclude-use-default: true
```

**Comment by jnan806** [comment]
@dewey 

maybe https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648 is useful for you to resolve it, but it is not be the best way

**Comment by jnan806** [comment]
@ldez  I resolved this issue by https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648, but I think it is not the best way. Because there is a param in .golangci.yaml like following:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/43714056/213058861-de415e58-3ebe-478d-855f-666a3532d9d7.png">
So does golangci-lint-action can exec with above param?

**Comment by ldez** [comment]
With the new version of the action (v3.6.0) you can now provide extra args to add extra output format.

Example:

```yaml
    - name: Golangci Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53.2
        args: --out-format=colored-line-number
```

https://golangci-lint.run/usage/configuration/#output-configuration

Related to #769
