### ISSUE TITLE
Import of modules where the module name in go.mod is different to the package name - linter gives Error: undeclared name (typecheck)

### ISSUE THREAD

**Issue by hyrefeldt-ourstudio** [golangci/golangci-lint-action#648]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

I have a situation where I want to import a private module for logging where the package name of that module is different from the name stated in its `go.mod`

In the `go.mod` of that module we have
```go
module github.com/some-org/go-logging

go 1.16
```

But in the `.go` files of that module the package statement at the top is 
```go
package logging

func SomeFunction() {
	...
}
```

Usually, it has been possible to access the module in our services like this.
```go
package main

import "github.com/some-org/go-logging"

func main() {
	logging.SomeFunction()
}
```
So the snippet above is an example of how the logging module is used in the repository where I run the golangci-lint-action. This kind of usage of the module has been working for a long time.

The problem is that I get this from the lint action for the file above.
```
Error: undeclared name: `logging` (typecheck)
```

I guess the linter doesn't understand that `github.com/some-org/go-logging` declares the name `logging`.

The project structure of the repository is
```
.
├- .github
|  └- workflows
|     └- workflow-file.yml
└- keto-proxy
    ├- main.go
    ├- go.mod
    └- go.sum
```

When I run this locally (which is what the action seem to run)
```
cd keto-proxy
golangci-lint run --out-format=github-actions --path-prefix=keto-proxy -E gofmt
```
there are no warnings.

I guess the easy way out is to replace my imports with aliased imports like
```go
package main

import logging "github.com/some-org/go-logging"

func main() {
	logging.SomeFunction()
}
```
which would make the declaration of `logging` explicit to the linter. But since this works locally and I couldn't find the relevant information in other issues I thought it might be best to put this here. Aliased imports should not be necessary here right?

### Version of golangci-lint

1.50.1

### Version of the GitHub Action

3.3.1

### Workflow file

<details>

```
on: [ push ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: extractions/netrc@v1
      with:
        machine: github.com
        username: login
        password: ${{ secrets.GH_TOKEN }}
    - name: Run linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.50.1
        args: -E gofmt
        working-directory: keto-proxy
```

</details>

### Go version

1.19.4

### Code example or link to a public repository

<details>

This is somewhat of a repetition of the description.

**The module**

```
.
├- someFunction.go
├- go.mod
└- go.sum
```

In `go.mod`:
```go
module github.com/some-org/go-logging

go 1.16

require (
	...
)
```

In `someFunction.go`:
```go
package logging

func SomeFunction() {
	...
}
```

**The repository where I use the module above and where the lint action is run**

```
.
├- .github
|  └- workflows
|     └- workflow-file.yml
└- keto-proxy
    ├- main.go
    ├- go.mod
    └- go.sum
```

In `main.go`:
```go
package main

import "github.com/some-org/go-logging"

func main() {
	logging.SomeFunction()
}
```

Output from setup-go action that is run prior to the golangci-lint action.
```
Run actions/setup-go@v3
  with:
    go-version: 1.19.x
    check-latest: false
    token: ***
    cache: false
Setup go version spec 1.19.x
Found in cache @ /opt/hostedtoolcache/go/1.19.4/x64
Added go to the path
Successfully set up Go version 1.19.x
go version go1.19.4 linux/amd64

go env
  GO111MODULE=""
  GOARCH="amd64"
  GOBIN=""
  GOCACHE="/home/runner/.cache/go-build"
  GOENV="/home/runner/.config/go/env"
  GOEXE=""
  GOEXPERIMENT=""
  GOFLAGS=""
  GOHOSTARCH="amd64"
  GOHOSTOS="linux"
  GOINSECURE=""
  GOMODCACHE="/home/runner/go/pkg/mod"
  GONOPROXY=""
  GONOSUMDB=""
  GOOS="linux"
  GOPATH="/home/runner/go"
  GOPRIVATE=""
  GOPROXY="https://proxy.golang.org,direct"
  GOROOT="/opt/hostedtoolcache/go/1.19.4/x64"
  GOSUMDB="sum.golang.org"
  GOTMPDIR=""
  GOTOOLDIR="/opt/hostedtoolcache/go/1.19.4/x64/pkg/tool/linux_amd64"
  GOVCS=""
  GOVERSION="go1.19.4"
  GCCGO="gccgo"
  GOAMD64="v1"
  AR="ar"
  CC="gcc"
  CXX="g++"
  CGO_ENABLED="1"
  GOMOD="/dev/null"
  GOWORK=""
  CGO_CFLAGS="-g -O[2](private url)"
  CGO_CPPFLAGS=""
  CGO_CXXFLAGS="-g -O2"
  CGO_FFLAGS="-g -O2"
  CGO_LDFLAGS="-g -O2"
  PKG_CONFIG="pkg-config"
  GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build272[3](private url)[8](private url)38[9](private url)[19](private url)=/tmp/go-build -gno-record-gcc-switches"
```

</details>
