### ISSUE TITLE
Unexpected HTTP response: 404 with v1.52.2

### ISSUE THREAD

**Issue by caevv** [golangci/golangci-lint-action#689]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

```
Run golangci/golangci-lint-action@v3
  with:
    version: v1.5[2](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:2).2
    only-new-issues: true
    args: --timeout [3](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:3)0m --out-${NO_FUTURE}format colored-line-number
    github-token: ***
    skip-cache: false
    skip-pkg-cache: false
    skip-build-cache: false
prepare environment
  Checking for go.mod: go.mod
  Finding needed golangci-lint version...
  Installing golangci-lint v1.52.2...
  Downloading https://github.com/golangci/golangci-lint/releases/download/v1.52.2/golangci-lint-1.52.2-linux-amd6[4](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:4).tar.gz ...
Error: Failed to run: Error: Unexpected HTTP response: 404, Error: Unexpected HTTP response: 404
    at /home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:6724:2[5](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:5)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/golangci/golangci-lint-action/v3/dist/run/index.js:[6](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:6)634:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Unexpected HTTP response: 404
Writing patch to /tmp/tmp-1[7](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:7)47-GBvNpCs5rNbO/pull.patch
Received 922746[8](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:8)8 of 1[9](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:9)06[10](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:11)648 (48.4%), 87.9 MBs/sec
Received 190610648 of 190610648 (100.0%), [11](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:12)8.7 MBs/sec
Cache Size: ~182 MB (190610648 B)
/usr/bin/tar -xf /home/runner/work/_temp/3cfa0497-285b-4105-80b6-01fcec880cc3/cache.tgz -P -C /home/runner/work/abc/abc -z
Cache restored successfully
Restored cache for golangci-lint from key 'golangci-lint.cache-2773-3fbbb88552f883da08007e2ec1a77d2fbef262fc' in [13](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:14)9[24](https://github.com/abc/abc/actions/runs/4284005137/jobs/7460352050#step:4:26)ms
```

### Version of golangci-lint

v1.52.2

### Version of the GitHub Action

v3

### Workflow file

<details>

```
name: "linters"

on:
  pull_request:
    paths:
      - "**.go"
      - ".github/workflows/linters.yml"
  push:
    branches:
      - master
    paths:
      - "**.go"

jobs:
  golangci-lint-annotations:
    name: golangci-lint-annotations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          only-new-issues: true
          args: "--timeout 30m --out-${NO_FUTURE}format colored-line-number"

```

</details>

### Go version

1.9

### Code example or link to a public repository

.
