### ISSUE TITLE
Action fails due to `musttag` checker without any other logs

### ISSUE THREAD

**Issue by snprajwal** [golangci/golangci-lint-action#714]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

Please see this workflow run: https://github.com/checkpoint-restore/go-criu/actions/runs/4499138717/jobs/7917225693

The workflow exits with the following logs:

```
  Running [/home/runner/golangci-lint-1.52.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
  level=warning msg="[runner] Can't run linter goanalysis_metalinter: musttag: running `go list all`: exit status 1"
  level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: musttag: running `go list all`: exit status 1\n\n"
  
  Error: golangci-lint exit with code 3
```

No other information is thrown, even during a debug run of the action.

golangci-lint itself runs successfully on the repo locally without raising any issues.

### Version of golangci-lint

v1.52.1

### Version of the GitHub Action

v3

### Workflow file

<details>

```
name: verify
on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        # Only show new issues for a pull request.
        only-new-issues: true
```

</details>

### Go version

Go 1.17

### Code example or link to a public repository

<details>

You can find the repo at https://github.com/checkpoint-restore/go-criu

</details>
