### ISSUE TITLE
Caching of the linting data causing timeout.

### ISSUE THREAD

**Issue by subhroacharjee** [golangci/golangci-lint-action#730]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

The issue at hand is related to the linting process, when the lint job is executed more than once with netrox/act on a local machine or in a GitHub Action, it gets timeout and even with timeout it takes a lot of time. Two example of run are as follows

> first run
![first run](https://user-images.githubusercontent.com/88422396/233261356-346de0a6-e2ee-41d6-a9c8-e033986c721e.png)
> second run
![second run](https://user-images.githubusercontent.com/88422396/233261614-44acbe38-ca95-4a07-a01c-c3c14282a8a3.png)

As per my understanding this problem arises when the golangci-lint tool, caches its data during the first run and reuses it on the second run. This causes the available memory to be reduced to less than 100mb, leading to a timeout error during the linting process. The error message indicates that there's not enough memory available to complete the process.
This problem has been identified by examining the logs from the production environment.

> production log from GH actions
![image](https://user-images.githubusercontent.com/88422396/233259599-4605265c-df2a-4a54-937b-794ee28a89b8.png)

One workaround to solve this issue is to add a timeout to the linting process, but this can significantly increase the time it takes to complete the job. This is not an ideal solution, as it can slow down the development process and cause delays. Given this delay is much higher than the cli tool, it's becomes really slower in comparison.

> same command in local cli
![image](https://user-images.githubusercontent.com/88422396/233265122-e2594d71-1c21-4f6d-82ba-e06d0eb54fb5.png)

### Version of golangci-lint

latest - 1.52.2

### Version of the GitHub Action

3

### Workflow file

<details>
setup-go uses actions/setup-go@v3 along with few other configuration to include the private vendors, install go dependencies and caching those dependecies.

```yaml
jobs:
  lint:
    name: Golang Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-go
        with:
          go-version: 1.18
          personal-access-token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
          only-new-issues: true
```

</details>

### Go version

1.18

### Code example or link to a public repository

Private repo code cant be shared.
<details>

```go
// add your code here
```

</details>
