### ISSUE TITLE
make it possible to set the GOOS / GOARCH

### ISSUE THREAD

**Issue by marten-seemann** [golangci/golangci-lint-action#742]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

I have a lot of platform-specific in [quic-go](https://github.com/quic-go/quic-go). So far, I've been running golangci-lint on Ubuntu, thus only the code for Linux has been linted.

I discovered that in the terminal, it's easily possible to run golangci-lint for other platforms as well:
```bash
GOOS=<x> GOARCH=<y> golangci-lint run .
```

As you might be able to expected, the code for the other platforms was not properly linted. I therefore would like to run golangci-lint using multiple platforms on CI. As far as I can see, there's no way to set the GOOS / GOARCH as a config flag.

As a workaround, this is how you could achieve the same result:
```yml
- name: Set GOOS environment variable
  run: echo "GOOS=windows" >> $GITHUB_ENV
- name: golangci-lint (Linux)
  uses: golangci/golangci-lint-action@v3
  with:
     version: v1.52.2
```

I suggest adding config flags to make this more accessible:
```yml
- name: golangci-lint (Linux)
  uses: golangci/golangci-lint-action@v3
  with:
     goos: "windows"
     goarch: "i386"
     version: v1.52.2
```

Does this make sense?

### Version of golangci-lint

v1.52.2

### Version of the GitHub Action

v3

### Workflow file

see above

### Go version

1.20

### Code example or link to a public repository

https://github.com/quic-go/quic-go/blob/22d6b0e626c56f311ff05705042d8caf506e5919/.github/workflows/lint.yml#L24-L35

**Comment by ldez** [comment]
I think a better solution is to use an OS matrix:

```yml
jobs:

  golangci-lint:
    name: Linter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
// ...
```
