### ISSUE TITLE
Issue running golangci-lint 1.53 via the action

### ISSUE THREAD

**Issue by iuliananz** [golangci/golangci-lint-action#760]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

We've started seeing this in our CI with the move to 1.53. No issues with 1.52.2. I tried with the default configuration or custom one, no difference.
On the local machine, it works fine with 1.53, it only fails in CI, thus I'm assuming there's something not working with how the action is setup

```
  Running [/root/golangci-lint-1.53.0-linux-amd64/golangci-lint run --out-format=github-actions --verbose --timeout 10m0s] in [] ...
  level=error msg="[linter] depguard: create analyzer: couldn't expand $gostd: could not read GOROOT directory: open src: no such file or directory\nmust have an Allow and/or Deny package list"
  
  Error: golangci-lint exit with code 3
  Ran golangci-lint in 83ms
```

Any idea how to fix it?

### Version of golangci-lint

1.53

### Version of the GitHub Action

3.4

### Workflow file

GO_VERSION: I've tried with both 1.19.9 and 1.20.4
<details>

```
 lint-go-files:
    name: lint-go-files
    runs-on: [ self-hosted, prod ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Setup Golang"
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Run lint"
        uses: golangci/golangci-lint-action@v3
        with:
          skip-pkg-cache: true
          skip-build-cache: true
          args: --verbose --timeout 10m0s
```

</details>

### Go version

1.20.4

### Code example or link to a public repository

<details>

```go
Not relevant, it'll fail any code, it has nothing to do with the actual code being linted.
```

</details>
