### ISSUE TITLE
stale caches -- any way to avoid or flush?

### ISSUE THREAD

**Issue by tmc** [golangci/golangci-lint-action#779]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

I maintain https://github.com/tmc/langchaingo and have encountered several apparent stale caches.

Locally and currently in CI I see

```
$ make lint
golangci-lint run --color=always --sort-results ./...
chains/llm.go:88:1: GetMemory returns interface (github.com/tmc/langchaingo/schema.Memory) (ireturn)
// GetOutputKeys returns the output keys the chain will return.
^
```

locally a cache clean fixes this but I don't see any way to do that with this action

### Version of golangci-lint

golangci-lint has version 1.52.2 built with go1.20.2 from da04413 on 2023-03-23T16:18:48Z

### Version of the GitHub Action

3.6.0

### Workflow file
```yml
name: ci

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: stable
          # Cache is managed by golangci-lint
          # https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: stable
          cache: false
      - uses: actions/checkout@v3
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
```
### Go version

1.20.5

### Code example or link to a public repository

<details>

https://github.com/tmc/langchaingo/actions/runs/5363122543/jobs/9730477729

</details>
