### ISSUE TITLE
typecheck error is not resulting in useful annotation

### ISSUE THREAD

**Issue by sgtsquiggs** [golangci/golangci-lint-action#802]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

Typecheck errors result in annotations that are not descriptive of the error and also are attached to the wrong files:

![image](https://github.com/golangci/golangci-lint-action/assets/3420325/2e0e5cc7-d089-46aa-b389-ae59a4805657)

![image](https://github.com/golangci/golangci-lint-action/assets/3420325/9a8a1b51-4302-4327-96e3-690ce3236de8)
![image](https://github.com/golangci/golangci-lint-action/assets/3420325/a2a9d8ef-888f-4e9c-add8-a94c4c27d99e)

### Version of golangci-lint

1.52.2

### Version of the GitHub Action

3

### Workflow file

<details>

```
(SNIP)
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2
          args: --verbose --timeout=15m --config=$FLEET_DAEDALUS_HOME/.golangci.yml
          skip-cache: true
          working-directory: src/daedalus/services/opsgate
(SNIP)
```

</details>

### Go version

1.20.6

### Code example or link to a public repository

<details>
Code triggering typecheck error:
```go
errors.Wrap(previousBusinessDateErr, "failed to get next business date", "Today date", today.Date)
```

</details>
