### ISSUE TITLE
annotations display on 2 PR (develop and staging, although I don't run golangci-lint in staging)

### ISSUE THREAD

**Issue by fpt-phongnx8** [golangci/golangci-lint-action#806]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Issue

-  annotations display on 2 PR (develop and staging, although I don't run golangci-lint in staging)

I create github feature branch: feature/feature-a

I create 2 PR
- from feature/feature-a to develop
- from feature/feature-a to staging

See code below, you can see golangci-lint-action run only create PR to develop branch. 
And when I create PR to staging branch, I will run another check, not golangci-lint-action

But I realize that annotations display at File changes on both 2 PR.

I don't know if this is the author's purpose.
I think It's bug.

### Version of golangci-lint

version: v1.53

### Version of the GitHub Action

golangci/golangci-lint-action@v3

### pull_request.yml
<details>

```
on:
    pull_request:
      branches: 
        - 'develop'
        - 'staging'

jobs:
  lint-check:
    name: golangci-lint
    if: github.event.pull_request.base.ref == 'develop'
    uses: ./.github/workflows/golangci-lint.yml

  container-security-check:
    name: container-security-check
    if: github.event.pull_request.base.ref == 'staging'
    uses: ./.github/workflows/container-security-check.yml
```

</details>

### golangci-lint.yml
<details>

```
# golangci-lint.yml (called workflow)
name: golangci-lint
on:
  workflow_call:
    inputs:
      working-directory:
        description: working directory
        type: string
        required: false
        default: "./"

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: ${{ inputs.working-directory }}go.mod
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        continue-on-error: true
        with:
          version: v1.53
          working-directory: ${{ inputs.working-directory }}
          args: --timeout=10m --config=${{ inputs.working-directory }}.golangci.yml
```

</details>

### Go version

1.20

### Code example or link to a public repository

<details>

```go

```

</details>
