### ISSUE TITLE
"File exists" errors when un-taring golangci-lint on upgrading to setup-go@v4 from setup-go@v3

### ISSUE THREAD

**Issue by Shwetha-Acharya** [golangci/golangci-lint-action#807]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

Error Snippet:

>Received 612368384 of 664124659 (92.2%), 116.3 MBs/sec
>Received 664124659 of 664124659 (100.0%), 118.2 MBs/sec
Cache Size: ~633 MB (664124659 B)
/usr/bin/tar -xf /home/runner/work/_temp/005209fb-aa88-4145-a3ef-1[26]
(https://github.com/RamenDR/ramen/actions/runs/5609819817/job/15198156789#step:4:27)4e395e5c7/cache.tzst -P -C
/home/runner/work/ramen/ramen --use-compress-program unzstd
Error: /usr/bin/tar: ../../../go/pkg/mod/sigs.k8s.io/yaml@v1.3.0/yaml_test.go: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/sigs.k8s.io/yaml@v1.3.0/LICENSE: Cannot open: File exists
/usr/bin/tar: ../../../go/pkg/mod/sigs.k8s.io/yaml@v1.3.0/code-of-conduct.md: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/sigs.k8s.io/yaml@v1.3.0/yaml.go: Cannot open: File exists

The issue can be resolved on setting cache: false with setup-golang:
```
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          
```

### Version of golangci-lint

v3

### Version of the GitHub Action

Latest

### Workflow file

```
  golangci:
    name: Golangci Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: GolangCI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
```

### Go version

v4

### Code example or link to a public repository

https://github.com/RamenDR/ramen/blob/main/.github/workflows/ci.yaml

**Comment by bombsimon** [comment]
This seems to be the only still open issue for this problem. Have you read through the different comments in #23, #244, #677?

**Comment by Shwetha-Acharya** [comment]
@bombsimon yes, I had come across all the above mentioned issues before.

We are already running unit tests after golangci-lint alraedy as mentioned in #23, which did not seem to help us much to mitigate the problem.
Setting cache:false as mentioned in #677 have only worked for us. (Refer our actual codebase: https://github.com/RamenDR/ramen/blob/main/.github/workflows/ci.yaml#L60)


This issue is raised because disabling cache is workaround, not a fix to this problem. 
We would want to encounter no errors even with cache on.

**Comment by rdonkin-attest** [comment]
Just ran into this error - it would be great to have a fix that enables good performance (which golangci-lint talks about in main README) by enabling caching without also having 16K lines of logs with file-exists errors.

**Comment by NfNitLoop** [comment]
We started running into this just today.  A few hours earlier, builds worked.  Now they're failing, with no changes to our go code or workflow.

```
Run golangci/golangci-lint-action@v3
  with:
    version: v1.52
    working-directory: components/cli/cli-app
    github-token: ***
    only-new-issues: false
    skip-cache: false
    skip-pkg-cache: false
    skip-build-cache: false
    install-mode: binary
```

[...]

`Checking for go.mod: components/cli/cli-app/go.mod
  Cache Size: ~202 MB (211431218 B)
  /usr/bin/tar -xf /home/runner/work/_temp/6c5bf7d7-95b3-4e82-b8bd-ece114577a62/cache.tzst -P -C /home/runner/work/$our_repo --use-compress-program unzstd
  Received 211431218 of 211431218 (100.0%), 201.6 MBs/sec
```

Followed by 9000+ lines of "Cannot open: file exists", and new lint errors that I suspect may be due to a broken go/pkg cache.  I'll try disabling the cache to see if that fixes us.
