### ISSUE TITLE
How to use private go modules dependencies?

### ISSUE THREAD

**Issue by steebchen** [golangci/golangci-lint-action#82]
How can I use private git repositories as go modules dependencies?

**Comment by SVilgelm** [comment]
```shell
git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
export GOPRIVATE="example.com"
```

**Comment by steebchen** [comment]
That didn't work for me, but


```
- name: Configure git for private modules
  env:
    TOKEN: ${{ secrets.YOUR_TOKEN }}
  run: git config --global url."https://YOUR_GITHUB_USERNAME:${TOKEN}@github.com".insteadOf "https://github.com"
```


did. Maybe you can add something like this in the readme so users can copy and paste it.

**Comment by bombsimon** [comment]
Personally I don't think thats something up to `golangci-lint` to document since it is true for all actions requiring access to other private repositories.

**Comment by SVilgelm** [comment]
Closing the issue

**Comment by bewuethr** [comment]
Since this is a highly ranked result when googling for private repos and how to use them with this action, here is an alternative that leverages functionality of `actions/checkout`:

```yaml
- name: Checkout repository
  uses: actions/checkout@v2
  with:
    # A personal access token with access to the private repos;
    # this is persisted for the rest of the workflow
    token: ${{ secrets.PAT_TOKEN }}

- name: Setup Go
  uses: actions/setup-go@v2
  with:
    go-version: 1.17

- name: Run golangci-lint
  uses: golangci/golangci-lint-action@v3
  env:
    # Tell the go command to not try the module proxy for these
    GOPRIVATE: github.com/yourorg
  with:
    version: v1.44
```
