### ISSUE TITLE
How to enable additional formatters?

### ISSUE THREAD

**Issue by steebchen** [golangci/golangci-lint-action#83]
Is there an option equivalent to the `--enable` flag?

**Comment by SVilgelm** [comment]
```yaml
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.30
          # Optional: golangci-lint command line arguments.
          args: --enable...
```
