### ISSUE TITLE
Can't run on windows/darwin specfic OS

### ISSUE THREAD

**Issue by corylanou** [golangci/golangci-lint-action#84]
Using the following configuration:

```yaml
name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
```

It will fail, as it tries to use the linux compiled binary.  The reason this won't work for our project is that we have `OS` specific files, such as `foo_darwin.go` and `foo_windows.go`.  I tested golangci-lint locally, and it will only lint files on that operating system, not all files (which makes sense).

Here is an example of my output locally:

```sh
$ golangci-lint run
greet/foo_darwin.go:11:1: receiver name k should be consistent with previous receiver name g for Greeter (golint)
func (k Greeter) By() {
^

corylanou@Corys-MacBook-Pro-Primary:~/tmp/go-lint
$ GOOS=windows golangci-lint run
greet/foo_windows.go:11:1: receiver name k should be consistent with previous receiver name g for Greeter (golint)
func (k Greeter) By() {
^
```

How do we go about specifying an action that knows to bring down the proper pre-compiled binary?
