### ISSUE TITLE
Incompatibility with go 1.21

### ISSUE THREAD

**Issue by Bluebugs** [golangci/golangci-lint-action#912]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

While using latest (v3 with 1.55.2), I get an error due to `unknown directive: toolchain`. This seems to be related to go 1.21 new toolchain directive. Using golangci-lint locally I do not have the problem. Not to sure what I am doing wrong here.

### Version of golangci-lint

1.55.2

### Version of the GitHub Action

v3

### Workflow file

```
name: Static Analysis
on: [push, pull_request]
permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
```

### Go version

1.21

### Code example or link to a public repository

The resulting action error: https://github.com/Bluebugs/rpi-poe-fan/actions/runs/7081901260/job/19271856132 .
