### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by juev** [golangci/golangci-lint-action#966]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

There is a pipepline using the latest version of golangci-lint-action. When you run it, warnings are displayed in the Github interface:

<img width="1357" alt="Screenshot 2024-02-09 at 10 09 57" src="https://github.com/golangci/golangci-lint-action/assets/114635/6fc8dbff-bda7-49ad-a077-9f7ff4c9bac8">

First:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: golangci/golangci-lint-action@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### Version of golangci-lint

last

### Version of the GitHub Action

golangci/golangci-lint-action@v3

### Workflow file

<details>

```
name: golangci-lint
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
```

</details>

### Go version

1.21

### Code example or link to a public repository

https://github.com/juev/wireproxy
