### ISSUE TITLE
Execution time takes too long with deafult GO111MODULE=on

### ISSUE THREAD

**Issue by Sortren** [golangci/golangci-lint-action#982]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

Example configuration provided in the README.md has default Go environment variables set, thus GO111MODULE is turned on at this point. Using this, execution time takes so long on Github Actions in comparison to the local run. With the basic list of linters (from golangci-lint.run docs): 
- errcheck
- gosimple
- govet
- ineffassign
- staticcheck
- unused

local execution: 20s
github actions execution with workflow file below: over 5 minutes

My fix to get close to the local execution time is to simply pass env: GO111MODULE=off. 
```yaml
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        env:
          GO111MODULE: off
        with:
          version: v1.54
```
Now the Github Actions execution takes about 40s, so it's drastically better than before.

My question is - what causes this particular issue and how does my fix "resolve" the issue? 
It would be nice to know what to do because documentation says nothing about turning off the go modules. 
I'm looking forward to get some explanation, this topic is really interesting and I have no clue what happens.

### Version of golangci-lint

1.54

### Version of the GitHub Action

4

### Workflow file

<details>

```
name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
```

</details>

### Go version

1.21

### Code example or link to a public repository

<details>

```go
// add your code here
```

</details>
