### ISSUE TITLE
cache upload hangs for 2 minutes after work is done

### ISSUE THREAD

**Issue by DavidS-ovm** [golangci/golangci-lint-action#984]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

The action hangs for 2 minutes after uploading the cache for no apparent reason.

See [this example](https://github.com/golangci/golangci-lint/actions/runs/8005893870/job/21866379885) from the golanci-lint main repo:

![2024-02-23_09MS+0100_1416x524](https://github.com/golangci/golangci-lint-action/assets/118179693/80945bfe-3af8-49f9-a16f-3448c4012414)

* This is not specific to golangci/golangci-lint setup, I've originally found this in my repos.
* When re-running the job (in my repo), the cache does not get uploaded and the delay vanishes.

### Version of golangci-lint

golangci-lint-1.56.2-linux-amd64

### Version of the GitHub Action

v4.0.0

### Workflow file

see https://github.com/golangci/golangci-lint/actions/runs/8005893870/workflow

### Go version

go version go1.22.0 linux/amd64

### Code example or link to a public repository

https://github.com/golangci/golangci-lint

**Comment by JeffreyTheTukkr** [comment]
Exactly the same issue here with a nearly empty project. 

![image](https://github.com/golangci/golangci-lint-action/assets/39796883/3554e811-28be-4ecf-bbc8-2c0c0f7a8168)

_ci.yaml_

```yaml
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56
      - run: golangci-lint run ./...
```
