### ISSUE TITLE
When a patch cannot be downloaded and `only-new-issues` is set, error instead of running

### ISSUE THREAD

**Issue by connorszczepaniak-wk** [golangci/golangci-lint-action#996]
### Welcome

- [X] Yes, I understand that the GitHub action repository is not the repository of golangci-lint itself.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### Description of the problem

I recently had a run of golangci-lint where the GitHub API responded with 422 downloading the patch for the PR. The PR was very small (6 lines, 1 file changed), but the API responded with the following:

`failed to fetch pull request patch: RequestError [HttpError]: The diff could not be processed because too many files changed`

This lint run has `only-new-issues` set, but without the patch it flagged a large number of issues in the entire repo because it ran without the patch.

It would be nice to have an option to error sooner and more obviously if the patch couldn't be downloaded instead of running the linter on the whole codebase. I understand that it may not be desirable for all use cases, so I propose making this a configuration option.

### Version of golangci-lint

1.56.2

### Version of the GitHub Action

4.0.0

### Workflow file

<details>

```
     - name: Lint Main
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804 # v4.0.0
        with:
          version: v1.56.2
          only-new-issues: true
          args: -v --timeout=10m
```

</details>

### Go version

1.22.0

### Code example or link to a public repository

N/A

**Comment by nielskrijger** [comment]
Same issue; Go 1.21, golangci-lint 1.55.1, Github action v4.

Was this introduced by V4?

At the moment this will happen for any PR with `--only-new-issues` that changes >300 files.

**Comment by connorszczepaniak-wk** [comment]
I just hit this even more explicitly:
`failed to fetch pull request patch: RequestError [HttpError]: Sorry, the diff exceeded the maximum number of lines (20000): {"resource":"PullRequest","field":"diff","code":"too_large"}`

I'm not sure what I'd want in this case. Failing would be bad, because then there'd be no way around it -- but I also don't want to run my linter on all code, because we have existing lints in our codebase that we haven't fixed yet (so it fails anyway).

**Comment by lcarva** [comment]
Is it possible to create the diff from the locally cloned repo instead? A git diff between the PR and the target branch should do the job, no?

**Comment by lcarva** [comment]
@ldez my bad... missed your comment.

> Solution 3 can work, but by default the action actions/checkout doesn't check out the full git tree (it only checks out 1 commit), so it will require adding fetch-depth: 0 to check out the full tree to be able to use git to create the diff. And, this is not an option that the golangci-lint action can control because it's an option from another action.

What if there was another parameter to the golangci-lint action, e.g. `use-local-clone` boolean? By default it is set to false which implies the current behavior. If it's set to true, then it just uses the local clone. It's up to users to make sure their local clone has the right depth. We could, however, have some sanity checks to help users along the way, e.g. if no diff is found, emit an error message that they should check the depth.

**Comment by ldez** [comment]
Please read once again my comment.

**Comment by lcarva** [comment]
> Please read once again my comment.

Hmm I'm likely missing something. My suggestion was to just use the git clone as is. Leaving it up to users to make sure it was cloned in the expected manner. I am not, by any means, suggesting that golangci-lint controls an option from another action.

**Comment by paul-freeman** [comment]
I'd like to suggest a Solution 4.

If the diff fails, you can continue doing the full diff lint, like it currently does. But if that lint run fails, you could return an error saying that the diff failed instead of showing all the linter errors from the full fallback scan.

But, at the end of the day, I think the only issue here is that the diff failure isn't obvious to the user when the fallback linter prints a lot of unrelated linter errors. So finding a way to surface what the real error is would be helpful.

**Comment by bsdlp** [comment]
```
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --new-from-rev=${{ github.event_name == 'pull_request' && format('origin/{0}', github.base_ref) || (github.event.before == '0000000000000000000000000000000000000000' && 'HEAD~1' || github.event.before) }}
```

bit of a hack but good enough for me without pulling out all of my hairs. `args: --new-from-merge-base=origin/${{ github.base_ref }}` didn't cover the pushes to main branch

**Comment by n-oden** [comment]
building on what @edjiang and @bsdlp did, I think this is roughly the best option for supporting large diffs without having to set `fetch-depth: 0` in the checkout stage:

```
jobs:
  golangci:
    name: Lint
    steps:
      - uses: actions/checkout@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          show-progress: false
      - run: |
          # shallow fetch the base sha and make a local head from it
          git fetch --no-tags --depth=1 origin ${{ github.event.pull_request.base.sha }}
          git checkout -b ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.base.sha }}
          # now do the same but for the PR sha and not-shallow
          git fetch --no-tags origin ${{ github.event.pull_request.head.sha }}
          git checkout -b ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.head.sha }}
          # make sure the PR sha is rebased on the current base; this prevents us from "linting" diffs
          # that are because of drift from the origin base branch
          git rebase ${{ github.event.pull_request.base.sha }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: >-
            --new-from-merge-base=${{ github.event.pull_request.base.ref }}
```
